/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITokenRegistryProvider, ITokenRegistryProviderInterface } from "../../CountryAllowModule.sol/ITokenRegistryProvider.js";

  const _abi = [
  {
    "inputs": [],
    "name": "identityRegistry",
    "outputs": [
      {
        "internalType": "contract IIdentityRegistry",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ITokenRegistryProvider__factory {
    static readonly abi = _abi;
    static createInterface(): ITokenRegistryProviderInterface {
      return new Interface(_abi) as ITokenRegistryProviderInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITokenRegistryProvider {
      return new Contract(address, _abi, runner) as unknown as ITokenRegistryProvider;
    }
  }
  