import type { Config } from "drizzle-kit";

export default {
  schema: [
    "./shared/schema.ts",
    "./shared/propertySchema.ts",
    "./shared/realEstateSchema.ts",
    "./shared/secondarySchema.ts",
    "./shared/axauSchema.ts",
    "./shared/treasurySchema.ts",
    "./shared/allocationPolicySchema.ts",
    "./shared/expansionSchema.ts",
    "./shared/stellarSchema.ts",
    "./shared/payrollSchema.ts",
    "./shared/rentSchema.ts",
    "./shared/capInfraSchema.ts",
    "./shared/agentGovSchema.ts",
    "./shared/bitgoSchema.ts",
    "./shared/bridgeSchema.ts",
    "./shared/circleSchema.ts",
    "./shared/contractSchema.ts",
    "./shared/cryptoCreditSchema.ts",
    "./shared/daoAccountSchema.ts",
    "./shared/distressedFeedSchema.ts",
    "./shared/docExtractionSchema.ts",
    "./shared/dueDiligenceSchema.ts",
    "./shared/erc3643Schema.ts",
    "./shared/escrowSchema.ts",
    "./shared/fieldIntelligenceSchema.ts",
    "./shared/keygrowSchema.ts",
    "./shared/launchAttestationsSchema.ts",
    "./shared/lendingFundSchema.ts",
    "./shared/networkIntelligenceSchema.ts",
    "./shared/onrampSchema.ts",
    "./shared/operatorStrategySchema.ts",
    "./shared/reserveAlertsSchema.ts",
    "./shared/reserveSnapshotsSchema.ts",
    "./shared/syndicationSchema.ts",
    "./shared/verifiedExecutionSchema.ts",
    "./shared/walletSchema.ts",
  ],
  out: "./migrations",
  dialect: "postgresql",
  strict: false,
  verbose: true,
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
} satisfies Config;
