/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AxiomStable3643FujiInterface extends Interface {
    getFunction(nameOrSignature: "AGENT_ROLE" | "BURNER_ROLE" | "DEFAULT_ADMIN_ROLE" | "MINTER_ROLE" | "allowance" | "approve" | "balanceOf" | "burn" | "compliance" | "decimals" | "forcedTransfer" | "freezeAddress" | "freezePartialTokens" | "getFrozenTokens" | "getRoleAdmin" | "grantRole" | "hasRole" | "identityRegistry" | "isFrozen" | "mint" | "name" | "onchainID" | "pause" | "paused" | "recoveryAddress" | "renounceRole" | "revokeRole" | "setCompliance" | "setIdentityRegistry" | "setOnchainID" | "supportsInterface" | "symbol" | "totalSupply" | "transfer" | "transferFrom" | "unfreezePartialTokens" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddressFrozen" | "Approval" | "ComplianceSet" | "ForcedTransfer" | "IdentityRegistrySet" | "OnchainIDSet" | "Paused" | "RecoverySuccess" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TokenPaused" | "TokenUnpaused" | "TokensFrozen" | "TokensUnfrozen" | "Transfer" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'AGENT_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'BURNER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MINTER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'burn', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'compliance', values?: undefined): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'forcedTransfer', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'freezeAddress', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'freezePartialTokens', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getFrozenTokens', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'identityRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'isFrozen', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'onchainID', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'recoveryAddress', values: [AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setCompliance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setIdentityRegistry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setOnchainID', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'unfreezePartialTokens', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'AGENT_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BURNER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MINTER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'compliance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'forcedTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freezeAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freezePartialTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFrozenTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'identityRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isFrozen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onchainID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recoveryAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCompliance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setIdentityRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOnchainID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unfreezePartialTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace AddressFrozenEvent {
      export type InputTuple = [userAddress: AddressLike, isFrozen: boolean, agentAddress: AddressLike];
      export type OutputTuple = [userAddress: string, isFrozen: boolean, agentAddress: string];
      export interface OutputObject {userAddress: string, isFrozen: boolean, agentAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ComplianceSetEvent {
      export type InputTuple = [compliance: AddressLike];
      export type OutputTuple = [compliance: string];
      export interface OutputObject {compliance: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ForcedTransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish, agent: AddressLike];
      export type OutputTuple = [from: string, to: string, amount: bigint, agent: string];
      export interface OutputObject {from: string, to: string, amount: bigint, agent: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityRegistrySetEvent {
      export type InputTuple = [registry: AddressLike];
      export type OutputTuple = [registry: string];
      export interface OutputObject {registry: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OnchainIDSetEvent {
      export type InputTuple = [onchainID: AddressLike];
      export type OutputTuple = [onchainID: string];
      export interface OutputObject {onchainID: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecoverySuccessEvent {
      export type InputTuple = [lostWallet: AddressLike, newWallet: AddressLike, investorOnchainID: AddressLike];
      export type OutputTuple = [lostWallet: string, newWallet: string, investorOnchainID: string];
      export interface OutputObject {lostWallet: string, newWallet: string, investorOnchainID: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenPausedEvent {
      export type InputTuple = [pausedBy: AddressLike];
      export type OutputTuple = [pausedBy: string];
      export interface OutputObject {pausedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenUnpausedEvent {
      export type InputTuple = [unpausedBy: AddressLike];
      export type OutputTuple = [unpausedBy: string];
      export interface OutputObject {unpausedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensFrozenEvent {
      export type InputTuple = [userAddress: AddressLike, amount: BigNumberish];
      export type OutputTuple = [userAddress: string, amount: bigint];
      export interface OutputObject {userAddress: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensUnfrozenEvent {
      export type InputTuple = [userAddress: AddressLike, amount: BigNumberish];
      export type OutputTuple = [userAddress: string, amount: bigint];
      export interface OutputObject {userAddress: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AxiomStable3643Fuji extends BaseContract {
    
    connect(runner?: ContractRunner | null): AxiomStable3643Fuji;
    waitForDeployment(): Promise<this>;

    interface: AxiomStable3643FujiInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    AGENT_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    BURNER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MINTER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    burn: TypedContractMethod<
      [_userAddress: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    compliance: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    forcedTransfer: TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    freezeAddress: TypedContractMethod<
      [_userAddress: AddressLike, _freeze: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    freezePartialTokens: TypedContractMethod<
      [_userAddress: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getFrozenTokens: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    identityRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isFrozen: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [_to: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    onchainID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    recoveryAddress: TypedContractMethod<
      [_lostWallet: AddressLike, _newWallet: AddressLike, _investorOnchainID: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setCompliance: TypedContractMethod<
      [_complianceAddr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setIdentityRegistry: TypedContractMethod<
      [_registryAddr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setOnchainID: TypedContractMethod<
      [_onchainIDAddr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    unfreezePartialTokens: TypedContractMethod<
      [_userAddress: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'AGENT_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'BURNER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MINTER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [_userAddress: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'compliance'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'forcedTransfer'): TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'freezeAddress'): TypedContractMethod<
      [_userAddress: AddressLike, _freeze: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'freezePartialTokens'): TypedContractMethod<
      [_userAddress: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getFrozenTokens'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'identityRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isFrozen'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [_to: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'onchainID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recoveryAddress'): TypedContractMethod<
      [_lostWallet: AddressLike, _newWallet: AddressLike, _investorOnchainID: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCompliance'): TypedContractMethod<
      [_complianceAddr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setIdentityRegistry'): TypedContractMethod<
      [_registryAddr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOnchainID'): TypedContractMethod<
      [_onchainIDAddr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unfreezePartialTokens'): TypedContractMethod<
      [_userAddress: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AddressFrozen'): TypedContractEvent<AddressFrozenEvent.InputTuple, AddressFrozenEvent.OutputTuple, AddressFrozenEvent.OutputObject>;
getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ComplianceSet'): TypedContractEvent<ComplianceSetEvent.InputTuple, ComplianceSetEvent.OutputTuple, ComplianceSetEvent.OutputObject>;
getEvent(key: 'ForcedTransfer'): TypedContractEvent<ForcedTransferEvent.InputTuple, ForcedTransferEvent.OutputTuple, ForcedTransferEvent.OutputObject>;
getEvent(key: 'IdentityRegistrySet'): TypedContractEvent<IdentityRegistrySetEvent.InputTuple, IdentityRegistrySetEvent.OutputTuple, IdentityRegistrySetEvent.OutputObject>;
getEvent(key: 'OnchainIDSet'): TypedContractEvent<OnchainIDSetEvent.InputTuple, OnchainIDSetEvent.OutputTuple, OnchainIDSetEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RecoverySuccess'): TypedContractEvent<RecoverySuccessEvent.InputTuple, RecoverySuccessEvent.OutputTuple, RecoverySuccessEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TokenPaused'): TypedContractEvent<TokenPausedEvent.InputTuple, TokenPausedEvent.OutputTuple, TokenPausedEvent.OutputObject>;
getEvent(key: 'TokenUnpaused'): TypedContractEvent<TokenUnpausedEvent.InputTuple, TokenUnpausedEvent.OutputTuple, TokenUnpausedEvent.OutputObject>;
getEvent(key: 'TokensFrozen'): TypedContractEvent<TokensFrozenEvent.InputTuple, TokensFrozenEvent.OutputTuple, TokensFrozenEvent.OutputObject>;
getEvent(key: 'TokensUnfrozen'): TypedContractEvent<TokensUnfrozenEvent.InputTuple, TokensUnfrozenEvent.OutputTuple, TokensUnfrozenEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'AddressFrozen(address,bool,address)': TypedContractEvent<AddressFrozenEvent.InputTuple, AddressFrozenEvent.OutputTuple, AddressFrozenEvent.OutputObject>;
      AddressFrozen: TypedContractEvent<AddressFrozenEvent.InputTuple, AddressFrozenEvent.OutputTuple, AddressFrozenEvent.OutputObject>;
    

      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ComplianceSet(address)': TypedContractEvent<ComplianceSetEvent.InputTuple, ComplianceSetEvent.OutputTuple, ComplianceSetEvent.OutputObject>;
      ComplianceSet: TypedContractEvent<ComplianceSetEvent.InputTuple, ComplianceSetEvent.OutputTuple, ComplianceSetEvent.OutputObject>;
    

      'ForcedTransfer(address,address,uint256,address)': TypedContractEvent<ForcedTransferEvent.InputTuple, ForcedTransferEvent.OutputTuple, ForcedTransferEvent.OutputObject>;
      ForcedTransfer: TypedContractEvent<ForcedTransferEvent.InputTuple, ForcedTransferEvent.OutputTuple, ForcedTransferEvent.OutputObject>;
    

      'IdentityRegistrySet(address)': TypedContractEvent<IdentityRegistrySetEvent.InputTuple, IdentityRegistrySetEvent.OutputTuple, IdentityRegistrySetEvent.OutputObject>;
      IdentityRegistrySet: TypedContractEvent<IdentityRegistrySetEvent.InputTuple, IdentityRegistrySetEvent.OutputTuple, IdentityRegistrySetEvent.OutputObject>;
    

      'OnchainIDSet(address)': TypedContractEvent<OnchainIDSetEvent.InputTuple, OnchainIDSetEvent.OutputTuple, OnchainIDSetEvent.OutputObject>;
      OnchainIDSet: TypedContractEvent<OnchainIDSetEvent.InputTuple, OnchainIDSetEvent.OutputTuple, OnchainIDSetEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RecoverySuccess(address,address,address)': TypedContractEvent<RecoverySuccessEvent.InputTuple, RecoverySuccessEvent.OutputTuple, RecoverySuccessEvent.OutputObject>;
      RecoverySuccess: TypedContractEvent<RecoverySuccessEvent.InputTuple, RecoverySuccessEvent.OutputTuple, RecoverySuccessEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TokenPaused(address)': TypedContractEvent<TokenPausedEvent.InputTuple, TokenPausedEvent.OutputTuple, TokenPausedEvent.OutputObject>;
      TokenPaused: TypedContractEvent<TokenPausedEvent.InputTuple, TokenPausedEvent.OutputTuple, TokenPausedEvent.OutputObject>;
    

      'TokenUnpaused(address)': TypedContractEvent<TokenUnpausedEvent.InputTuple, TokenUnpausedEvent.OutputTuple, TokenUnpausedEvent.OutputObject>;
      TokenUnpaused: TypedContractEvent<TokenUnpausedEvent.InputTuple, TokenUnpausedEvent.OutputTuple, TokenUnpausedEvent.OutputObject>;
    

      'TokensFrozen(address,uint256)': TypedContractEvent<TokensFrozenEvent.InputTuple, TokensFrozenEvent.OutputTuple, TokensFrozenEvent.OutputObject>;
      TokensFrozen: TypedContractEvent<TokensFrozenEvent.InputTuple, TokensFrozenEvent.OutputTuple, TokensFrozenEvent.OutputObject>;
    

      'TokensUnfrozen(address,uint256)': TypedContractEvent<TokensUnfrozenEvent.InputTuple, TokensUnfrozenEvent.OutputTuple, TokensUnfrozenEvent.OutputObject>;
      TokensUnfrozen: TypedContractEvent<TokensUnfrozenEvent.InputTuple, TokensUnfrozenEvent.OutputTuple, TokensUnfrozenEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }