/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CountryAllowModuleInterface extends Interface {
    getFunction(nameOrSignature: "addAllowedCountry" | "batchAllowCountries" | "bindCompliance" | "isComplianceBound" | "isCountryAllowed" | "moduleBurnAction" | "moduleCheck" | "moduleMintAction" | "moduleTransferAction" | "name" | "owner" | "removeAllowedCountry" | "renounceOwnership" | "setAllowAll" | "transferOwnership" | "unbindCompliance"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AllowAllSet" | "ComplianceBound" | "ComplianceUnbound" | "CountryAllowed" | "CountryDisallowed" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'addAllowedCountry', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'batchAllowCountries', values: [AddressLike, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'bindCompliance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isComplianceBound', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isCountryAllowed', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'moduleBurnAction', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleCheck', values: [AddressLike, AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleMintAction', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleTransferAction', values: [AddressLike, AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeAllowedCountry', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAllowAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unbindCompliance', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addAllowedCountry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchAllowCountries', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bindCompliance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isComplianceBound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCountryAllowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleBurnAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleMintAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleTransferAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAllowedCountry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAllowAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbindCompliance', data: BytesLike): Result;
  }

  
    export namespace AllowAllSetEvent {
      export type InputTuple = [compliance: AddressLike, allowAll: boolean];
      export type OutputTuple = [compliance: string, allowAll: boolean];
      export interface OutputObject {compliance: string, allowAll: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ComplianceBoundEvent {
      export type InputTuple = [compliance: AddressLike];
      export type OutputTuple = [compliance: string];
      export interface OutputObject {compliance: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ComplianceUnboundEvent {
      export type InputTuple = [compliance: AddressLike];
      export type OutputTuple = [compliance: string];
      export interface OutputObject {compliance: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CountryAllowedEvent {
      export type InputTuple = [compliance: AddressLike, country: BigNumberish];
      export type OutputTuple = [compliance: string, country: bigint];
      export interface OutputObject {compliance: string, country: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CountryDisallowedEvent {
      export type InputTuple = [compliance: AddressLike, country: BigNumberish];
      export type OutputTuple = [compliance: string, country: bigint];
      export interface OutputObject {compliance: string, country: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CountryAllowModule extends BaseContract {
    
    connect(runner?: ContractRunner | null): CountryAllowModule;
    waitForDeployment(): Promise<this>;

    interface: CountryAllowModuleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addAllowedCountry: TypedContractMethod<
      [_compliance: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    batchAllowCountries: TypedContractMethod<
      [_compliance: AddressLike, _countries: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    bindCompliance: TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isComplianceBound: TypedContractMethod<
      [_compliance: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isCountryAllowed: TypedContractMethod<
      [_compliance: AddressLike, _country: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    moduleBurnAction: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    moduleCheck: TypedContractMethod<
      [arg0: AddressLike, _to: AddressLike, arg2: BigNumberish, _compliance: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    moduleMintAction: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    moduleTransferAction: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeAllowedCountry: TypedContractMethod<
      [_compliance: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setAllowAll: TypedContractMethod<
      [_compliance: AddressLike, _allow: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unbindCompliance: TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addAllowedCountry'): TypedContractMethod<
      [_compliance: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'batchAllowCountries'): TypedContractMethod<
      [_compliance: AddressLike, _countries: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'bindCompliance'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isComplianceBound'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isCountryAllowed'): TypedContractMethod<
      [_compliance: AddressLike, _country: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'moduleBurnAction'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'moduleCheck'): TypedContractMethod<
      [arg0: AddressLike, _to: AddressLike, arg2: BigNumberish, _compliance: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'moduleMintAction'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'moduleTransferAction'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeAllowedCountry'): TypedContractMethod<
      [_compliance: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAllowAll'): TypedContractMethod<
      [_compliance: AddressLike, _allow: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unbindCompliance'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AllowAllSet'): TypedContractEvent<AllowAllSetEvent.InputTuple, AllowAllSetEvent.OutputTuple, AllowAllSetEvent.OutputObject>;
getEvent(key: 'ComplianceBound'): TypedContractEvent<ComplianceBoundEvent.InputTuple, ComplianceBoundEvent.OutputTuple, ComplianceBoundEvent.OutputObject>;
getEvent(key: 'ComplianceUnbound'): TypedContractEvent<ComplianceUnboundEvent.InputTuple, ComplianceUnboundEvent.OutputTuple, ComplianceUnboundEvent.OutputObject>;
getEvent(key: 'CountryAllowed'): TypedContractEvent<CountryAllowedEvent.InputTuple, CountryAllowedEvent.OutputTuple, CountryAllowedEvent.OutputObject>;
getEvent(key: 'CountryDisallowed'): TypedContractEvent<CountryDisallowedEvent.InputTuple, CountryDisallowedEvent.OutputTuple, CountryDisallowedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'AllowAllSet(address,bool)': TypedContractEvent<AllowAllSetEvent.InputTuple, AllowAllSetEvent.OutputTuple, AllowAllSetEvent.OutputObject>;
      AllowAllSet: TypedContractEvent<AllowAllSetEvent.InputTuple, AllowAllSetEvent.OutputTuple, AllowAllSetEvent.OutputObject>;
    

      'ComplianceBound(address)': TypedContractEvent<ComplianceBoundEvent.InputTuple, ComplianceBoundEvent.OutputTuple, ComplianceBoundEvent.OutputObject>;
      ComplianceBound: TypedContractEvent<ComplianceBoundEvent.InputTuple, ComplianceBoundEvent.OutputTuple, ComplianceBoundEvent.OutputObject>;
    

      'ComplianceUnbound(address)': TypedContractEvent<ComplianceUnboundEvent.InputTuple, ComplianceUnboundEvent.OutputTuple, ComplianceUnboundEvent.OutputObject>;
      ComplianceUnbound: TypedContractEvent<ComplianceUnboundEvent.InputTuple, ComplianceUnboundEvent.OutputTuple, ComplianceUnboundEvent.OutputObject>;
    

      'CountryAllowed(address,uint16)': TypedContractEvent<CountryAllowedEvent.InputTuple, CountryAllowedEvent.OutputTuple, CountryAllowedEvent.OutputObject>;
      CountryAllowed: TypedContractEvent<CountryAllowedEvent.InputTuple, CountryAllowedEvent.OutputTuple, CountryAllowedEvent.OutputObject>;
    

      'CountryDisallowed(address,uint16)': TypedContractEvent<CountryDisallowedEvent.InputTuple, CountryDisallowedEvent.OutputTuple, CountryDisallowedEvent.OutputObject>;
      CountryDisallowed: TypedContractEvent<CountryDisallowedEvent.InputTuple, CountryDisallowedEvent.OutputTuple, CountryDisallowedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }