/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface IdentityRegistryStorageInterface extends Interface {
    getFunction(nameOrSignature: "addIdentityToStorage" | "contains" | "getIdentity" | "getInvestorCountry" | "getInvestors" | "owner" | "removeIdentityFromStorage" | "renounceOwnership" | "transferOwnership" | "updateCountryInStorage" | "updateIdentityInStorage"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CountryUpdated" | "IdentityRemoved" | "IdentityStored" | "IdentityUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'addIdentityToStorage', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'contains', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getIdentity', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getInvestorCountry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getInvestors', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeIdentityFromStorage', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateCountryInStorage', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateIdentityInStorage', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addIdentityToStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contains', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getIdentity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvestorCountry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvestors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeIdentityFromStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCountryInStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateIdentityInStorage', data: BytesLike): Result;
  }

  
    export namespace CountryUpdatedEvent {
      export type InputTuple = [userAddress: AddressLike, country: BigNumberish];
      export type OutputTuple = [userAddress: string, country: bigint];
      export interface OutputObject {userAddress: string, country: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityRemovedEvent {
      export type InputTuple = [userAddress: AddressLike];
      export type OutputTuple = [userAddress: string];
      export interface OutputObject {userAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityStoredEvent {
      export type InputTuple = [userAddress: AddressLike, identity: AddressLike, country: BigNumberish];
      export type OutputTuple = [userAddress: string, identity: string, country: bigint];
      export interface OutputObject {userAddress: string, identity: string, country: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityUpdatedEvent {
      export type InputTuple = [userAddress: AddressLike, newIdentity: AddressLike];
      export type OutputTuple = [userAddress: string, newIdentity: string];
      export interface OutputObject {userAddress: string, newIdentity: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IdentityRegistryStorage extends BaseContract {
    
    connect(runner?: ContractRunner | null): IdentityRegistryStorage;
    waitForDeployment(): Promise<this>;

    interface: IdentityRegistryStorageInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addIdentityToStorage: TypedContractMethod<
      [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    contains: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getIdentity: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [string],
      'view'
    >
    

    
    getInvestorCountry: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getInvestors: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeIdentityFromStorage: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateCountryInStorage: TypedContractMethod<
      [_userAddress: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateIdentityInStorage: TypedContractMethod<
      [_userAddress: AddressLike, _newIdentity: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addIdentityToStorage'): TypedContractMethod<
      [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contains'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getIdentity'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getInvestorCountry'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getInvestors'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeIdentityFromStorage'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCountryInStorage'): TypedContractMethod<
      [_userAddress: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateIdentityInStorage'): TypedContractMethod<
      [_userAddress: AddressLike, _newIdentity: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CountryUpdated'): TypedContractEvent<CountryUpdatedEvent.InputTuple, CountryUpdatedEvent.OutputTuple, CountryUpdatedEvent.OutputObject>;
getEvent(key: 'IdentityRemoved'): TypedContractEvent<IdentityRemovedEvent.InputTuple, IdentityRemovedEvent.OutputTuple, IdentityRemovedEvent.OutputObject>;
getEvent(key: 'IdentityStored'): TypedContractEvent<IdentityStoredEvent.InputTuple, IdentityStoredEvent.OutputTuple, IdentityStoredEvent.OutputObject>;
getEvent(key: 'IdentityUpdated'): TypedContractEvent<IdentityUpdatedEvent.InputTuple, IdentityUpdatedEvent.OutputTuple, IdentityUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'CountryUpdated(address,uint16)': TypedContractEvent<CountryUpdatedEvent.InputTuple, CountryUpdatedEvent.OutputTuple, CountryUpdatedEvent.OutputObject>;
      CountryUpdated: TypedContractEvent<CountryUpdatedEvent.InputTuple, CountryUpdatedEvent.OutputTuple, CountryUpdatedEvent.OutputObject>;
    

      'IdentityRemoved(address)': TypedContractEvent<IdentityRemovedEvent.InputTuple, IdentityRemovedEvent.OutputTuple, IdentityRemovedEvent.OutputObject>;
      IdentityRemoved: TypedContractEvent<IdentityRemovedEvent.InputTuple, IdentityRemovedEvent.OutputTuple, IdentityRemovedEvent.OutputObject>;
    

      'IdentityStored(address,address,uint16)': TypedContractEvent<IdentityStoredEvent.InputTuple, IdentityStoredEvent.OutputTuple, IdentityStoredEvent.OutputObject>;
      IdentityStored: TypedContractEvent<IdentityStoredEvent.InputTuple, IdentityStoredEvent.OutputTuple, IdentityStoredEvent.OutputObject>;
    

      'IdentityUpdated(address,address)': TypedContractEvent<IdentityUpdatedEvent.InputTuple, IdentityUpdatedEvent.OutputTuple, IdentityUpdatedEvent.OutputObject>;
      IdentityUpdated: TypedContractEvent<IdentityUpdatedEvent.InputTuple, IdentityUpdatedEvent.OutputTuple, IdentityUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }