/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TransferLimitModuleInterface extends Interface {
    getFunction(nameOrSignature: "bindCompliance" | "getDailyUsage" | "getTransferLimit" | "isComplianceBound" | "isExempt" | "moduleBurnAction" | "moduleCheck" | "moduleMintAction" | "moduleTransferAction" | "name" | "owner" | "renounceOwnership" | "setExempt" | "setTransferLimit" | "transferOwnership" | "unbindCompliance"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ComplianceBound" | "ComplianceUnbound" | "ExemptionSet" | "OwnershipTransferred" | "TransferLimitSet"): EventFragment;

    encodeFunctionData(functionFragment: 'bindCompliance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getDailyUsage', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getTransferLimit', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isComplianceBound', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isExempt', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleBurnAction', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleCheck', values: [AddressLike, AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleMintAction', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleTransferAction', values: [AddressLike, AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setExempt', values: [AddressLike, AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setTransferLimit', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unbindCompliance', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'bindCompliance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDailyUsage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTransferLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isComplianceBound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isExempt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleBurnAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleMintAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleTransferAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setExempt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTransferLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbindCompliance', data: BytesLike): Result;
  }

  
    export namespace ComplianceBoundEvent {
      export type InputTuple = [compliance: AddressLike];
      export type OutputTuple = [compliance: string];
      export interface OutputObject {compliance: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ComplianceUnboundEvent {
      export type InputTuple = [compliance: AddressLike];
      export type OutputTuple = [compliance: string];
      export interface OutputObject {compliance: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExemptionSetEvent {
      export type InputTuple = [compliance: AddressLike, wallet: AddressLike, exempt: boolean];
      export type OutputTuple = [compliance: string, wallet: string, exempt: boolean];
      export interface OutputObject {compliance: string, wallet: string, exempt: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferLimitSetEvent {
      export type InputTuple = [compliance: AddressLike, limit: BigNumberish];
      export type OutputTuple = [compliance: string, limit: bigint];
      export interface OutputObject {compliance: string, limit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TransferLimitModule extends BaseContract {
    
    connect(runner?: ContractRunner | null): TransferLimitModule;
    waitForDeployment(): Promise<this>;

    interface: TransferLimitModuleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bindCompliance: TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getDailyUsage: TypedContractMethod<
      [_compliance: AddressLike, _wallet: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getTransferLimit: TypedContractMethod<
      [_compliance: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    isComplianceBound: TypedContractMethod<
      [_compliance: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isExempt: TypedContractMethod<
      [_compliance: AddressLike, _wallet: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    moduleBurnAction: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    moduleCheck: TypedContractMethod<
      [_from: AddressLike, arg1: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    moduleMintAction: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    moduleTransferAction: TypedContractMethod<
      [_from: AddressLike, arg1: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setExempt: TypedContractMethod<
      [_compliance: AddressLike, _wallet: AddressLike, _isExempt: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setTransferLimit: TypedContractMethod<
      [_compliance: AddressLike, _limit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unbindCompliance: TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bindCompliance'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getDailyUsage'): TypedContractMethod<
      [_compliance: AddressLike, _wallet: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTransferLimit'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isComplianceBound'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isExempt'): TypedContractMethod<
      [_compliance: AddressLike, _wallet: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'moduleBurnAction'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'moduleCheck'): TypedContractMethod<
      [_from: AddressLike, arg1: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'moduleMintAction'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'moduleTransferAction'): TypedContractMethod<
      [_from: AddressLike, arg1: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setExempt'): TypedContractMethod<
      [_compliance: AddressLike, _wallet: AddressLike, _isExempt: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTransferLimit'): TypedContractMethod<
      [_compliance: AddressLike, _limit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unbindCompliance'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ComplianceBound'): TypedContractEvent<ComplianceBoundEvent.InputTuple, ComplianceBoundEvent.OutputTuple, ComplianceBoundEvent.OutputObject>;
getEvent(key: 'ComplianceUnbound'): TypedContractEvent<ComplianceUnboundEvent.InputTuple, ComplianceUnboundEvent.OutputTuple, ComplianceUnboundEvent.OutputObject>;
getEvent(key: 'ExemptionSet'): TypedContractEvent<ExemptionSetEvent.InputTuple, ExemptionSetEvent.OutputTuple, ExemptionSetEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TransferLimitSet'): TypedContractEvent<TransferLimitSetEvent.InputTuple, TransferLimitSetEvent.OutputTuple, TransferLimitSetEvent.OutputObject>;

    filters: {
      
      'ComplianceBound(address)': TypedContractEvent<ComplianceBoundEvent.InputTuple, ComplianceBoundEvent.OutputTuple, ComplianceBoundEvent.OutputObject>;
      ComplianceBound: TypedContractEvent<ComplianceBoundEvent.InputTuple, ComplianceBoundEvent.OutputTuple, ComplianceBoundEvent.OutputObject>;
    

      'ComplianceUnbound(address)': TypedContractEvent<ComplianceUnboundEvent.InputTuple, ComplianceUnboundEvent.OutputTuple, ComplianceUnboundEvent.OutputObject>;
      ComplianceUnbound: TypedContractEvent<ComplianceUnboundEvent.InputTuple, ComplianceUnboundEvent.OutputTuple, ComplianceUnboundEvent.OutputObject>;
    

      'ExemptionSet(address,address,bool)': TypedContractEvent<ExemptionSetEvent.InputTuple, ExemptionSetEvent.OutputTuple, ExemptionSetEvent.OutputObject>;
      ExemptionSet: TypedContractEvent<ExemptionSetEvent.InputTuple, ExemptionSetEvent.OutputTuple, ExemptionSetEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TransferLimitSet(address,uint256)': TypedContractEvent<TransferLimitSetEvent.InputTuple, TransferLimitSetEvent.OutputTuple, TransferLimitSetEvent.OutputObject>;
      TransferLimitSet: TypedContractEvent<TransferLimitSetEvent.InputTuple, TransferLimitSetEvent.OutputTuple, TransferLimitSetEvent.OutputObject>;
    
    };
  }