/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IIdentityRegistry__factory } from './IIdentityRegistry__factory.js';
export { IModularCompliance__factory } from './IModularCompliance__factory.js';
export { IModule__factory } from './IModule__factory.js';