[package]
name = "axiom_claim_prototype"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.72.1" }

[addresses]
axiom_claim_prototype = "0x0"
