/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AbstractModule', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AbstractModule__factory>
getContractFactory(name: 'AxiomStable3643', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AxiomStable3643__factory>
getContractFactory(name: 'AxiomStable3643Fuji', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AxiomStable3643Fuji__factory>
getContractFactory(name: 'CountryAllowModule', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CountryAllowModule__factory>
getContractFactory(name: 'ITokenRegistryProvider', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITokenRegistryProvider__factory>
getContractFactory(name: 'TransferLimitModule', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TransferLimitModule__factory>
getContractFactory(name: 'IIdentityRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IIdentityRegistry__factory>
getContractFactory(name: 'IModularCompliance', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IModularCompliance__factory>
getContractFactory(name: 'IModule', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IModule__factory>

  getContractAt(name: 'AbstractModule', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AbstractModule>
getContractAt(name: 'AxiomStable3643', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AxiomStable3643>
getContractAt(name: 'AxiomStable3643Fuji', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AxiomStable3643Fuji>
getContractAt(name: 'CountryAllowModule', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CountryAllowModule>
getContractAt(name: 'ITokenRegistryProvider', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITokenRegistryProvider>
getContractAt(name: 'TransferLimitModule', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TransferLimitModule>
getContractAt(name: 'IIdentityRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IIdentityRegistry>
getContractAt(name: 'IModularCompliance', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IModularCompliance>
getContractAt(name: 'IModule', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IModule>

  deployContract(name: 'AbstractModule', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AbstractModule>
deployContract(name: 'AxiomStable3643', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AxiomStable3643>
deployContract(name: 'AxiomStable3643Fuji', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AxiomStable3643Fuji>
deployContract(name: 'CountryAllowModule', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CountryAllowModule>
deployContract(name: 'ITokenRegistryProvider', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITokenRegistryProvider>
deployContract(name: 'TransferLimitModule', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TransferLimitModule>
deployContract(name: 'IIdentityRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IIdentityRegistry>
deployContract(name: 'IModularCompliance', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IModularCompliance>
deployContract(name: 'IModule', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IModule>

  deployContract(name: 'AbstractModule', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AbstractModule>
deployContract(name: 'AxiomStable3643', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AxiomStable3643>
deployContract(name: 'AxiomStable3643Fuji', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AxiomStable3643Fuji>
deployContract(name: 'CountryAllowModule', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CountryAllowModule>
deployContract(name: 'ITokenRegistryProvider', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITokenRegistryProvider>
deployContract(name: 'TransferLimitModule', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TransferLimitModule>
deployContract(name: 'IIdentityRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IIdentityRegistry>
deployContract(name: 'IModularCompliance', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IModularCompliance>
deployContract(name: 'IModule', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IModule>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  