export const NAV_ITEMS = [
  { name: 'Start', href: '/' },
  { name: 'Learn', href: '/academy' },
  { name: 'Connect', href: '/susu', step: 'connect' },
  { name: 'Save Together', href: '/susu', step: 'save' },
  { name: 'Grow', href: '/keygrow' },
  { name: 'Advanced', href: '/bank', isDropdown: true },
  { name: 'About', href: '/about-us' },
];

export const MOBILE_NAV_ITEMS = [
  { name: 'Start', href: '/' },
  { name: 'Learn', href: '/academy' },
  { name: 'Connect & Save', href: '/susu' },
  { name: 'Wealth Practice', href: '/learn-wealth-practice' },
  { name: 'Grow', href: '/keygrow' },
  { name: 'Buy AXM', href: '/buy-axm' },
  { name: 'Staking', href: '/staking' },
  { name: 'Training', href: '/organizer-dashboard' },
  { name: 'About', href: '/about-us' },
];

export const ADVANCED_DROPDOWN = [
  { name: 'Wealth Practice', href: '/learn-wealth-practice' },
  { name: 'Wealth Dashboard', href: '/wealth-dashboard' },
  { name: 'Organizer Training', href: '/organizer-dashboard' },
  { name: 'Buy AXM', href: '/buy-axm' },
  { name: 'Treasury', href: '/bank' },
  { name: 'DEX Exchange', href: '/dex' },
  { name: 'Staking', href: '/staking' },
  { name: 'Wealth Engine', href: '/veaxm-leaderboard' },
  { name: 'Yield Vault', href: '/yield-vault' },
  { name: 'Rewards', href: '/rewards' },
  { name: 'V2 Analytics', href: '/v2-analytics' },
  { name: 'Credit Builder', href: '/credit-builder' },
  { name: 'Referrals', href: '/referrals' },
  { name: 'Badges', href: '/badges' },
  { name: 'Group Analytics', href: '/group-analytics' },
  { name: 'Axiom Nodes', href: '/axiom-nodes' },
  { name: 'Governance', href: '/governance' },
  { name: 'Create Proposal', href: '/governance/create' },
  { name: 'Notifications', href: '/notifications' },
  { name: 'Transparency', href: '/transparency-dashboard' },
  { name: 'Launchpad', href: '/launchpad' },
  { name: 'Impact', href: '/impact' },
  { name: 'Admin', href: '/admin/whitelist' },
];

export const FOOTER_ECOSYSTEM = [
  { name: 'Join a Purpose Group', href: '/purpose-group-onboarding' },
  { name: 'Learn (Academy)', href: '/academy' },
  { name: 'Connect & Save (SUSU)', href: '/susu' },
  { name: 'Wealth Practice', href: '/learn-wealth-practice' },
  { name: 'Buy AXM', href: '/buy-axm' },
  { name: 'Grow (KeyGrow)', href: '/keygrow' },
  { name: 'Treasury', href: '/bank' },
  { name: 'Staking', href: '/staking' },
  { name: 'DEX Exchange', href: '/dex' },
  { name: 'Node Network', href: '/axiom-nodes' },
  { name: 'Governance', href: '/governance' },
  { name: 'PMA Trust', href: '/pma' },
];

export const FOOTER_RESOURCES = [
  { name: 'My Journey', href: '/journey' },
  { name: 'Community Stories', href: '/community' },
  { name: 'Equity Calculator', href: '/tools/equity-calculator' },
  { name: 'Graduation Dashboard', href: '/graduation-dashboard' },
  { name: 'Analytics', href: '/v2-analytics' },
  { name: 'Credit Builder', href: '/credit-builder' },
  { name: 'Rewards', href: '/rewards' },
  { name: 'Referrals', href: '/referrals' },
  { name: 'Badges', href: '/badges' },
  { name: 'Yield Vault', href: '/yield-vault' },
  { name: 'Community Impact', href: '/impact' },
  { name: 'Whitepaper', href: '/whitepaper' },
  { name: 'Transparency', href: '/transparency-dashboard' },
  { name: 'FAQ', href: '/faq' },
];

export const FOOTER_COMPANY = [
  { name: 'About Us', href: '/about-us' },
  { name: 'Team', href: '/team' },
  { name: 'SMS Alerts', href: '/sms-alerts' },
  { name: 'Terms of Service', href: '/terms-and-conditions' },
  { name: 'Privacy Policy', href: '/privacy-policy' },
  { name: 'Compliance', href: '/transparency?tab=compliance' },
  { name: 'Admin Dashboard', href: '/admin/treasury' },
  { name: 'Whitelist Management', href: '/admin/whitelist' },
  { name: 'SUSU Admin', href: '/susu/admin' },
  { name: 'Error Logs', href: '/admin/error-logs' },
];
