/**
 * AXIOM Protocol — Active Contract Configuration
 * AUTO-GENERATED by scripts/verify-active-contracts.js
 * Generated: 2026-02-10T04:02:41.251Z
 *
 * DO NOT EDIT MANUALLY. Run: npm run verify:contracts
 *
 * CRITICAL: DO NOT MIX ecosystems.
 * Never deposit PRIMARY AXUSD into Euler Vault.
 * Never report EULER AXUSD metrics as public supply.
 *
 * Selection method:
 *   ACTIVE_AXUSD: Highest totalSupply among verified Axiom AXUSD contracts on Arbitrum One
 *   EULER_AXUSD:  Derived from Euler Vault.asset() on-chain call (immutable binding)
 *   ACTIVE_PSM:   PSM paired with ACTIVE_AXUSD (GENIUS ecosystem)
 *   EULER_PSM:    PSM paired with EULER_AXUSD (Original ecosystem)
 *
 * Evidence:
 *   ACTIVE_AXUSD supply: 1000048.91
 *   EULER_AXUSD supply:  156.503658781
 *   Euler Vault asset(): 0xA7907b6B6169D66012Bf1c36f27a72C06AEC065c
 *   Revenue Router axusd(): 0xA7907b6B6169D66012Bf1c36f27a72C06AEC065c
 */

export const DO_NOT_MIX = 'Never deposit PRIMARY AXUSD into Euler Vault and never report EULER AXUSD metrics as public supply.' as const;

export const ACTIVE_AXUSD = '0x73585df5E62a5E85E6dd6b1df3C08E00eee5b89C' as const;

export const ACTIVE_PSM = '0x5db58d9c21369d1532a48Bdd658E4Fe415404922' as const;

export const EULER_AXUSD = '0xA7907b6B6169D66012Bf1c36f27a72C06AEC065c' as const;

export const EULER_PSM = '0x4584888cB411E9cc88e3800BAB73A430D90d3793' as const;

export const ACTIVE_CONTRACTS = {
  axusd: {
    primary: ACTIVE_AXUSD,
    euler: EULER_AXUSD,
    label: {
      primary: 'GENIUS Act Aligned AXUSD (Jan 11, 2026)',
      euler: 'Original AxiomStable (Jan 5, 2026) — Euler Vault binding',
    },
  },
  psm: {
    primary: ACTIVE_PSM,
    euler: EULER_PSM,
    label: {
      primary: 'GENIUS PSM — 5M ceiling (Jan 11, 2026)',
      euler: 'Original PSM — 500K ceiling (Jan 5, 2026)',
    },
  },
  /** @deprecated V4 vault — hook config prevents new deposits; WITHDRAW_ONLY mode */
  eulerVaultDeprecated: '0xe3048078286eA27fF91Eed10AA5FD749F0Ce7059' as const,
  revenueRouter: '0x39A9Ca593d350450d93aF7F24dC1A682df47F30a' as const,
  seed: '0xdfcdc9bB6486Eb06e2885fAb590AE67796c35046' as const,
  axmToken: '0x864F9c6f50dC5Bd244F5002F1B0873Cd80e2539D' as const,
  treasuryHub: '0x3fD63728288546AC41dAe3bf25ca383061c3A929' as const,
  deployer: '0x8d7892CF226B43d48B6e3ce988A1274e6D114C96' as const,

  // ── Lending Fund Contracts (v7 deployed 2026-03-22, Maple-style grace period, keccak loanId) ──
  // AXIOMFixedLoan:    Fixed-term loan engine (draw tranches, amortized/interest-only, prepayment)
  // AXIOMCreditMarket: LP pool with ERC-3643 IdentityRegistry gating (Wildcat V2 pattern)
  // NOTE: creditMarket and fixedLoanNFT are IDENTICAL to the exported CREDIT_MARKET_ADDRESS /
  // FIXED_LOAN_NFT_ADDRESS constants below — both sources must stay in sync.
  creditMarket: '0xeE21B3C0D89b8EfD9eD61A7FD0B98A637eA9ab37' as const,
  fixedLoanNFT: '0x96634c2E1E80Fa51d45F0e9aB9F49B7dB3e9c859' as const,
} as const;

/** v7 CreditMarket — deployed + verified Arbitrum Blockscout 2026-03-22 */
export const CREDIT_MARKET_ADDRESS = '0x85074a74774568692128eE97Da661Fe49dcF5fE4' as const;
/** v7 FixedLoan NFT — deployed + verified Arbitrum Blockscout 2026-03-22 */
export const FIXED_LOAN_NFT_ADDRESS = '0x511A0cD642532585dc87e41C84f7f499a9755511' as const;
/** ERC-3643 IdentityRegistry — canonical Axiom protocol registry (Arbitrum One) */
export const IDENTITY_REGISTRY_ADDRESS = '0x58f64a1262d5434d6C7637a2309b0999bB6D1970' as const;

/**
 * ERC-7726 Oracle Adapter — PENDING_DEPLOYMENT
 * Source: contracts/oracle/AXIOMOracleAdapter.sol
 * Deploy: npx hardhat run scripts/deploy-axusd-oracle.js --network arbitrumOne
 * After deploying, update this address and AXUSD_ORACLE_ADAPTER in src/config/oracleConfig.ts.
 * Interface: getQuote(uint256 inAmount, address base, address quote) → uint256 outAmount
 * Pairs: USDC↔AXUSD, USDT↔AXUSD, WETH→AXUSD, ARB→AXUSD, WBTC→AXUSD
 */
export const ERC7726_ORACLE_ADAPTER_ADDRESS = '0xc894d1500CB1FBf8F045e87bd357A51345197c4e' as const;

/**
 * EVK Open Money Market — ERC-3643 AXUSD Open Lending Vault (Task #38)
 * Status: DEPLOYED ✓
 * Vault name: eAXUSD-6 | Deployed via Euler V2 EVK factory on Arbitrum One
 * Asset: ERC-3643 AXUSD (0xD6110F59A978aDa6eF5c0E9D6BaA04455D46Ade7)
 * Oracle: AXIOMOracleAdapter v2 (0xc894d1500CB1FBf8F045e87bd357A51345197c4e) — immutable
 * UoA: USDC | Collateral: USDC at 90% borrowLTV / 95% liquidationLTV
 * Supply Cap: 1M AXUSD | Borrow Cap: 500K AXUSD
 * IRM: IRMLinearKink (1% base, 5%@kink 80%, 100% max)
 * Whitelisted in LendingPlatformModule ✓ | EVC whitelisted in LPM ✓
 */
export const EVK_OPEN_MARKET_VAULT_ADDRESS = '0xacdA87801f6409bB5157BA78aF1BD9631d6609B2' as const;
export const EVK_OPEN_MARKET_IRM_ADDRESS = '0x13B4F093C95785a621b928A9fa31Ea7a7fAb1662' as const;
/** Governor admin of the EVK vault — Axiom deployer EOA at launch; transfer to multisig post-seeding */
export const EVK_OPEN_MARKET_GOVERNOR_ADDRESS = '0x8d7892CF226B43d48B6e3ce988A1274e6D114C96' as const;

/** Returns true when the EVK Open Market vault has been deployed */
export function isEvkVaultDeployed(): boolean {
  return true; // eAXUSD-6 is live at 0xacdA87801f6409bB5157BA78aF1BD9631d6609B2
}

// ── Euler Earn AXUSD Vault (Task #39) ──
// Status: PENDING_DEPLOYMENT | run scripts/deploy-axusd-euler-earn-vault.js then update these.
export const EULER_EARN_VAULT_ADDRESS = '0x0000000000000000000000000000000000000000' as const;
export const EULER_EARN_FACTORY_ADDRESS = '0x0000000000000000000000000000000000000000' as const;
/** AxiomFeeBurner — receives 10% performance fee from Euler Earn vault */
export const AXIOM_FEE_BURNER_ADDRESS = '0xF5d59581Eb0fd024aC1b2B67f1B290832eb8Cb94' as const;

/** Returns true when the Euler Earn AXUSD vault has been deployed */
export function isEulerEarnDeployed(): boolean {
  return EULER_EARN_VAULT_ADDRESS !== '0x0000000000000000000000000000000000000000';
}

// ── EulerSwap AXUSD Liquidity Layer (Task #40) ──
// Status: PENDING_DEPLOYMENT | run scripts/deploy-eulerswap-pools.js then update these.
// EulerSwap pools earn dual yield: swap fees + lending yield from EVK vault backing.
// ERC-3643 prerequisite: pool addresses must be whitelisted in LendingPlatformModule.
export const EULER_SWAP_FACTORY_ADDRESS = '0x0000000000000000000000000000000000000000' as const;
export const EULER_SWAP_AXUSD_USDC_POOL_ADDRESS = '0x0000000000000000000000000000000000000000' as const;
export const EULER_SWAP_AXUSD_AXM_POOL_ADDRESS = '0x0000000000000000000000000000000000000000' as const;

/** Returns true when the EulerSwap AXUSD/USDC pool has been deployed */
export function isEulerSwapDeployed(): boolean {
  return EULER_SWAP_AXUSD_USDC_POOL_ADDRESS !== '0x0000000000000000000000000000000000000000';
}

export const LEGACY_ADDRESSES = [
  { address: '0x8616E8EA83f048ab9A5eC513c9412dd2993bcE3F', reason: 'handleUSD (fxUSD) — NOT Axiom, false reference' },
  { address: '0xe3048078286eA27fF91Eed10AA5FD749F0Ce7059', reason: 'Euler AXUSD Vault V4 (eAXUSD-4) — deprecated, WITHDRAW_ONLY mode; hook config issue prevents new deposits; replaced by EVK_OPEN_MARKET_VAULT' },
  { address: '0xCf00A6FA6f5bAc1f224Cee029DacF3b8CCC79429', reason: 'Euler AXUSD Vault V3 — deprecated, broken hook config' },
  { address: '0x1045B6c70AC7b491bf724B5Aa4D89F542D955E15', reason: 'Legacy Euler PRICE_ORACLE — superseded by ERC7726_ORACLE_ADAPTER_ADDRESS once deployed' },
  { address: '0xE3b1f38AaBAd138d0EF2e2C7429ee57c512fDF3D', reason: 'Legacy OracleAdapter (Phase 3) — superseded by ERC7726_ORACLE_ADAPTER_ADDRESS once deployed' },
] as const;

export function assertActiveContracts(): void {
  const required = [ACTIVE_AXUSD, ACTIVE_PSM, EULER_AXUSD, EULER_PSM];
  for (const addr of required) {
    if (!addr || !addr.match(/^0x[0-9a-fA-F]{40}$/)) {
      throw new Error(`Invalid active contract address: ${addr}`);
    }
  }
}
