/**
 * AXIOM Protocol — Active Contract Configuration
 * AUTO-GENERATED by scripts/verify-active-contracts.js
 * Generated: 2026-02-10T04:02:41.251Z
 *
 * DO NOT EDIT MANUALLY. Run: npm run verify:contracts
 *
 * CRITICAL: DO NOT MIX ecosystems.
 * Never deposit PRIMARY AXUSD into Euler Vault.
 * Never report EULER AXUSD metrics as public supply.
 *
 * Selection method:
 *   ACTIVE_AXUSD: Highest totalSupply among verified Axiom AXUSD contracts on Arbitrum One
 *   EULER_AXUSD:  Derived from Euler Vault.asset() on-chain call (immutable binding)
 *   ACTIVE_PSM:   PSM paired with ACTIVE_AXUSD (GENIUS ecosystem)
 *   EULER_PSM:    PSM paired with EULER_AXUSD (Original ecosystem)
 *
 * Evidence:
 *   ACTIVE_AXUSD supply: 1000048.91
 *   EULER_AXUSD supply:  156.503658781
 *   Euler Vault asset(): 0xA7907b6B6169D66012Bf1c36f27a72C06AEC065c
 *   Revenue Router axusd(): 0xA7907b6B6169D66012Bf1c36f27a72C06AEC065c
 */

export const DO_NOT_MIX = 'Never deposit PRIMARY AXUSD into Euler Vault and never report EULER AXUSD metrics as public supply.' as const;

export const ACTIVE_AXUSD = '0x73585df5E62a5E85E6dd6b1df3C08E00eee5b89C' as const;

export const ACTIVE_PSM = '0x5db58d9c21369d1532a48Bdd658E4Fe415404922' as const;

export const EULER_AXUSD = '0xA7907b6B6169D66012Bf1c36f27a72C06AEC065c' as const;

export const EULER_PSM = '0x4584888cB411E9cc88e3800BAB73A430D90d3793' as const;

export const ACTIVE_CONTRACTS = {
  axusd: {
    primary: ACTIVE_AXUSD,
    euler: EULER_AXUSD,
    label: {
      primary: 'GENIUS Act Aligned AXUSD (Jan 11, 2026)',
      euler: 'Original AxiomStable (Jan 5, 2026) — Euler Vault binding',
    },
  },
  psm: {
    primary: ACTIVE_PSM,
    euler: EULER_PSM,
    label: {
      primary: 'GENIUS PSM — 5M ceiling (Jan 11, 2026)',
      euler: 'Original PSM — 500K ceiling (Jan 5, 2026)',
    },
  },
  eulerVault: '0xe3048078286eA27fF91Eed10AA5FD749F0Ce7059' as const,
  revenueRouter: '0x39A9Ca593d350450d93aF7F24dC1A682df47F30a' as const,
  seed: '0xdfcdc9bB6486Eb06e2885fAb590AE67796c35046' as const,
  axmToken: '0x864F9c6f50dC5Bd244F5002F1B0873Cd80e2539D' as const,
  treasuryHub: '0x3fD63728288546AC41dAe3bf25ca383061c3A929' as const,
  deployer: '0x8d7892CF226B43d48B6e3ce988A1274e6D114C96' as const,

  // ── Lending Fund Contracts (v4 deployed 2026-03-22, ERC-3643 + draw schedule) ────
  // AXIOMFixedLoan:    Fixed-term loan engine (draw tranches, amortized/interest-only, prepayment)
  // AXIOMCreditMarket: LP pool with ERC-3643 IdentityRegistry gating (Wildcat V2 pattern)
  creditMarket: '0x42b0e50593ae6d6595F33448058074F88A4958C8' as const,
  fixedLoanNFT: '0xc4d12133f74c0f46F6aD00Bd930DAA75BF68801a' as const,
} as const;

export const CREDIT_MARKET_ADDRESS = '0x42b0e50593ae6d6595F33448058074F88A4958C8' as const;
export const FIXED_LOAN_NFT_ADDRESS = '0xc4d12133f74c0f46F6aD00Bd930DAA75BF68801a' as const;

export const LEGACY_ADDRESSES = [
  { address: '0x8616E8EA83f048ab9A5eC513c9412dd2993bcE3F', reason: 'handleUSD (fxUSD) — NOT Axiom, false reference' },
  { address: '0xCf00A6FA6f5bAc1f224Cee029DacF3b8CCC79429', reason: 'Euler AXUSD Vault V3 — deprecated, broken hook config' },
] as const;

export function assertActiveContracts(): void {
  const required = [ACTIVE_AXUSD, ACTIVE_PSM, EULER_AXUSD, EULER_PSM];
  for (const addr of required) {
    if (!addr || !addr.match(/^0x[0-9a-fA-F]{40}$/)) {
      throw new Error(`Invalid active contract address: ${addr}`);
    }
  }
}
