/**
 * AXIOM Credit Market v8 — Deployed Contract Addresses
 * Generated by scripts/deploy-credit-market.ts
 * Deployed: 2026-03-22 on Arbitrum One (chainId: 42161)
 *
 * AXIOMFixedLoan v8: Fixed-term loan engine
 *   - accrueAfterMaturity: controls whether interest accrues past dueAt
 *   - disburseTranche() calls creditMarket.disburseCommittedLiquidity() internally (onlyFixedLoan)
 *   - chargeOffLoan() path for written-off defaults
 *   - closeUndrawnApprovedLoan() path for APPROVED loans cancelled before disbursement
 * AXIOMCreditMarket v2: Permissioned LP pool (ERC-3643 IdentityRegistry gating)
 *   - disburseCommittedLiquidity() gated onlyFixedLoan — eliminates operator-callable disburse risk
 *   - writeDownOutstanding() for charge-off accounting
 *   - ArithmeticInvariantViolation guard on receiveRepayment
 *
 * Post-deploy wiring (completed in deploy script):
 *   fixedLoan.setCreditMarket(creditMarket) — tx: 0x38a956a54e46fef9fac026d038dbaf7843b12ae486a88de8df28edae382b27fd
 *   creditMarket.setFixedLoan(fixedLoan)    — tx: 0x8d00ac283940fb0a597f318fc8c253a556adbd3c1ef09469902cd2ec9dfa032e
 *
 * OPERATOR_ROLE authority path:
 *   Both contracts grant OPERATOR_ROLE to msg.sender (deployer) at construction.
 *   The deployer address is the Axiom Protocol multisig / operator wallet.
 *   Grant OPERATOR_ROLE to additional signers via grantRole(OPERATOR_ROLE, address).
 *   CreditMarket.disburseCommittedLiquidity() uses onlyFixedLoan (address check),
 *   so no cross-contract role grant is needed between the two contracts.
 *
 * NOTE: Addresses below are pending v8 redeployment. Run deploy-credit-market.ts to update.
 *   AXIOMFixedLoan:    https://arbitrum.blockscout.com/address/0x96634c2E1E80Fa51d45F0e9aB9F49B7dB3e9c859#code
 *   AXIOMCreditMarket: https://arbitrum.blockscout.com/address/0xeE21B3C0D89b8EfD9eD61A7FD0B98A637eA9ab37#code
 */

export const CREDIT_MARKET_DEPLOYMENT = {
  network:           'Arbitrum One',
  chainId:           42161,
  deployedAt:        '2026-03-22',
  deployer:          '0x8d7892CF226B43d48B6e3ce988A1274e6D114C96',

  axusd:             '0x73585df5E62a5E85E6dd6b1df3C08E00eee5b89C',
  identityRegistry:  '0x58f64a1262d5434d6C7637a2309b0999bB6D1970',
  creditMarket:      '0xeE21B3C0D89b8EfD9eD61A7FD0B98A637eA9ab37',
  fixedLoan:         '0x96634c2E1E80Fa51d45F0e9aB9F49B7dB3e9c859',

  explorerBase:      'https://arbitrum.blockscout.com',

  wireTxSetCreditMarket: '0x38a956a54e46fef9fac026d038dbaf7843b12ae486a88de8df28edae382b27fd',
  wireTxSetFixedLoan:    '0x8d00ac283940fb0a597f318fc8c253a556adbd3c1ef09469902cd2ec9dfa032e',

  roles: {
    operatorRole:    '0x97667070c54ef182b0f5858b034beac1b6f3089aa2d3188bb1e8929f4fa9b929',
    adminRole:       '0x0000000000000000000000000000000000000000000000000000000000000000',
  },

  loanStatusMap: {
    0: 'PENDING',
    1: 'APPROVED',
    2: 'ACTIVE',
    3: 'DELINQUENT',
    4: 'DEFAULTED',
    5: 'REPAID',
    6: 'CLOSED',
    7: 'CHARGED_OFF',
  } as Record<number, string>,

  paymentModes: {
    0: 'AMORTIZED',
    1: 'INTEREST_ONLY',
  } as Record<number, string>,
} as const;

// AXIOMFixedLoan v8 — fixed-term loan engine
export const FIXED_LOAN_ABI = [
  'function originateLoan(bytes32 loanId, address borrower, uint8 paymentMode, uint256 rateBps, uint256 prepayBps, uint256 graceSecs, uint256 termSecs, string calldata propAddress, uint256[] calldata trancheAmounts, uint256[] calldata trancheRelease) external',
  'function approveLoan(bytes32 loanId) external',
  'function disburseTranche(bytes32 loanId, uint8 trancheIndex) external',
  'function repayLoan(bytes32 loanId, uint256 paymentAmount) external',
  'function prepayLoan(bytes32 loanId) external',
  'function markDelinquent(bytes32 loanId) external',
  'function cureDelinquent(bytes32 loanId) external',
  'function defaultLoan(bytes32 loanId) external',
  'function closeUndrawnApprovedLoan(bytes32 loanId) external',
  'function chargeOffLoan(bytes32 loanId) external',
  'function setCreditMarket(address creditMarket) external',
  'function getLoan(bytes32 loanId) view returns (tuple(bytes32 loanId, address borrower, uint8 paymentMode, uint256 interestRateBps, uint256 prepayPenaltyBps, uint256 gracePeriodSeconds, uint256 termSeconds, uint256 startedAt, uint256 dueAt, uint8 state, uint256 totalPrincipal, uint256 drawnPrincipal, uint256 outstandingPrincipal, uint256 pendingInterest, uint256 lastAccrualAt, uint256 totalInterestPaid, uint256 totalPrincipalPaid, uint8 numTranches, tuple(uint256 amount, uint256 releaseAt, bool drawn) tranche0, tuple(uint256 amount, uint256 releaseAt, bool drawn) tranche1, tuple(uint256 amount, uint256 releaseAt, bool drawn) tranche2, string propertyAddress, uint256 delinquentAt, uint256 totalInstallments, uint256 installmentIntervalSeconds, uint256 installmentAmount, uint256 nextInstallmentDueAt, uint256 currentInstallmentPaid, uint256 installmentsSatisfied))',
  'function accruedInterest(bytes32 loanId) view returns (uint256)',
  'function nextPaymentDue(bytes32 loanId) view returns (uint256 amount, uint256 dueTimestamp)',
  'function paymentSchedule(bytes32 loanId) view returns (uint256[] amounts, uint256[] dueDates)',
  'function daysDelinquent(bytes32 loanId) view returns (uint256)',
  'function loanCount() view returns (uint256)',
  'function creditMarket() view returns (address)',
  'function identityRegistry() view returns (address)',
  'function accrueAfterMaturity() view returns (bool)',
  'function allLoanIds(uint256) view returns (bytes32)',
  'event LoanOriginated(bytes32 indexed loanId, address indexed borrower, uint256 totalPrincipal, string propertyAddress)',
  'event LoanApproved(bytes32 indexed loanId)',
  'event DrawDisbursed(bytes32 indexed loanId, uint8 trancheIndex, uint256 amount)',
  'event LoanPayment(bytes32 indexed loanId, address indexed payer, uint256 paymentAmount, uint256 interestPortion, uint256 principalPortion, uint256 remainingPrincipal)',
  'event LoanPrepaid(bytes32 indexed loanId, uint256 penaltyAmount)',
  'event LoanDelinquent(bytes32 indexed loanId, uint256 delinquentAt)',
  'event LoanCured(bytes32 indexed loanId)',
  'event LoanDefaulted(bytes32 indexed loanId)',
  'event LoanRepaid(bytes32 indexed loanId)',
  'event LoanClosed(bytes32 indexed loanId, uint256 releasedCommitment)',
  'event LoanChargedOff(bytes32 indexed loanId, uint256 principalWrittenOff, uint256 interestCleared)',
  'event CreditMarketSet(address indexed creditMarket)',
] as const;

// AXIOMCreditMarket v2 — permissioned LP pool (ERC-3643 identity-gated)
export const CREDIT_MARKET_ABI = [
  'function depositLiquidity(uint256 amountUsd) external',
  'function withdrawLiquidity(uint256 sharesToBurn) external',
  'function commitLiquidity(bytes32 loanId, uint256 amountUsd) external',
  'function claimInterest() external',
  'function setReserveRatio(uint256 newBps) external',
  'function setFixedLoan(address fixedLoan) external',
  'function availableLiquidity() view returns (uint256)',
  'function totalPoolValue() view returns (uint256)',
  'function sharePrice() view returns (uint256)',
  'function pendingInterest(address lp) view returns (uint256)',
  'function isLpVerified(address lp) view returns (bool)',
  'function lpShares(address) view returns (uint256)',
  'function totalLpShares() view returns (uint256)',
  'function totalDeposited() view returns (uint256)',
  'function totalInterestReceived() view returns (uint256)',
  'function totalPrincipalWrittenDown() view returns (uint256)',
  'function loanCommitment(bytes32) view returns (uint256)',
  'function reserveRatioBps() view returns (uint256)',
  'function fixedLoan() view returns (address)',
  'function identityRegistry() view returns (address)',
  'event LiquidityDeposited(address indexed lp, uint256 amountUsd, uint256 sharesIssued)',
  'event LiquidityWithdrawn(address indexed lp, uint256 axusdOut, uint256 sharesBurned)',
  'event LiquidityCommitted(bytes32 indexed loanId, uint256 amount)',
  'event LoanDisbursed(bytes32 indexed loanId, address indexed borrower, uint256 amount)',
  'event RepaymentReceived(bytes32 indexed loanId, uint256 principalReturned, uint256 interestReceived)',
  'event UndrawnCommitmentReleased(bytes32 indexed loanId, uint256 amount)',
  'event OutstandingWrittenDown(bytes32 indexed loanId, uint256 amount)',
  'event InterestClaimed(address indexed lp, uint256 amount)',
] as const;
