/**
 * AXIOM Credit Market v5 — Deployed Contract Addresses
 * Generated by scripts/deploy-credit-market.ts
 * Deployed: 2026-03-22 on Arbitrum One (chainId: 42161)
 *
 * AXIOMFixedLoan: Fixed-term loan engine (draw schedule, amortized/interest-only, prepayment)
 *   - Calls CreditMarket.receiveRepayment() after each borrower repayment
 *   - disburseTranche() records state; operator calls CreditMarket.disburseLoan() for capital
 * AXIOMCreditMarket: Permissioned LP pool (ERC-3643 IdentityRegistry gating)
 *   - AXUSD custody; disburses to borrowers, receives repayments from FixedLoan
 *   - pro-rata interestPerShare distribution to LPs
 *
 * Verification:
 *   AXIOMFixedLoan:    https://arbitrum.blockscout.com/address/0x4De489Ec2215e727de608A7016C2933967b3F33b#code
 *   AXIOMCreditMarket: https://arbitrum.blockscout.com/address/0x491E519c7377EcdE720d861f759ccBD6486A59F2#code
 *
 * Wiring (post-deploy):
 *   FixedLoan.creditMarket → CreditMarket (repayment callback, set via setCreditMarket)
 *   CreditMarket.fixedLoan → FixedLoan (auth gate on receiveRepayment, set via setFixedLoan)
 *   CreditMarket has OPERATOR_ROLE on FixedLoan
 */

export const CREDIT_MARKET_DEPLOYMENT = {
  network:           'Arbitrum One',
  chainId:           42161,
  deployedAt:        '2026-03-22',
  deployer:          '0x8d7892CF226B43d48B6e3ce988A1274e6D114C96',

  axusd:             '0x73585df5E62a5E85E6dd6b1df3C08E00eee5b89C',
  identityRegistry:  '0x58f64a1262d5434d6C7637a2309b0999bB6D1970',
  creditMarket:      '0x491E519c7377EcdE720d861f759ccBD6486A59F2',
  fixedLoan:         '0x4De489Ec2215e727de608A7016C2933967b3F33b',

  explorerBase:      'https://arbitrum.blockscout.com',

  roles: {
    operatorRole:    '0x97667070c54ef182b0f5858b034beac1b6f3089aa2d3188bb1e8929f4fa9b929',
    adminRole:       '0x0000000000000000000000000000000000000000000000000000000000000000',
  },

  loanStatusMap: {
    0: 'PENDING',
    1: 'APPROVED',
    2: 'ACTIVE',
    3: 'DELINQUENT',
    4: 'DEFAULTED',
    5: 'REPAID',
  } as Record<number, string>,

  paymentModes: {
    0: 'AMORTIZED',
    1: 'INTEREST_ONLY',
  } as Record<number, string>,
} as const;

// AXIOMFixedLoan — fixed-term loan engine (state machine; AXUSD custody in CreditMarket)
export const FIXED_LOAN_ABI = [
  'function originateLoan(bytes32 loanId, address borrower, uint8 paymentMode, uint256 rateBps, uint256 prepayBps, uint256 graceSecs, uint256 termSecs, string calldata propAddress, uint256[] calldata tranchAmts, uint256[] calldata tranchRelease) external',
  'function approveLoan(bytes32 loanId) external',
  'function disburseTranche(bytes32 loanId, uint8 trancheIndex) external',
  'function repayLoan(bytes32 loanId, uint256 paymentAmt) external',
  'function prepayLoan(bytes32 loanId) external',
  'function markDelinquent(bytes32 loanId) external',
  'function cureDelinquent(bytes32 loanId) external',
  'function defaultLoan(bytes32 loanId) external',
  'function closeLoan(bytes32 loanId) external',
  'function setCreditMarket(address creditMarket) external',
  'function getLoan(bytes32 loanId) view returns (tuple(bytes32 loanId, address borrower, uint8 paymentMode, uint256 interestRateBps, uint256 prepayPenaltyBps, uint256 gracePeriodSeconds, uint256 termSeconds, uint256 startedAt, uint256 dueAt, uint8 state, uint256 totalPrincipal, uint256 drawnPrincipal, uint256 outstandingPrincipal, uint256 pendingInterest, uint256 lastAccrualAt, uint256 totalInterestPaid, uint256 totalPrincipalPaid, uint8 numTranches, tuple(uint256 amount, uint256 releaseAt, bool drawn) tranche0, tuple(uint256 amount, uint256 releaseAt, bool drawn) tranche1, tuple(uint256 amount, uint256 releaseAt, bool drawn) tranche2, string propertyAddress))',
  'function accruedInterest(bytes32 loanId) view returns (uint256)',
  'function nextPaymentDue(bytes32 loanId) view returns (uint256 amount, uint256 dueTimestamp)',
  'function paymentSchedule(bytes32 loanId) view returns (uint256[] amounts, uint256[] dueDates)',
  'function daysDelinquent(bytes32 loanId) view returns (uint256)',
  'function creditMarket() view returns (address)',
  'function identityRegistry() view returns (address)',
  'function allLoanIds(uint256) view returns (bytes32)',
  'event LoanOriginated(bytes32 indexed loanId, address indexed borrower, uint256 totalPrincipal, string propertyAddress)',
  'event LoanApproved(bytes32 indexed loanId)',
  'event DrawDisbursed(bytes32 indexed loanId, uint8 trancheIndex, uint256 amount)',
  'event LoanPayment(bytes32 indexed loanId, address indexed payer, uint256 paymentAmount, uint256 interestPortion, uint256 principalPortion, uint256 remainingPrincipal)',
  'event LoanPrepaid(bytes32 indexed loanId, uint256 penaltyAmount)',
  'event LoanDelinquent(bytes32 indexed loanId)',
  'event LoanCured(bytes32 indexed loanId)',
  'event LoanDefaulted(bytes32 indexed loanId)',
  'event LoanRepaid(bytes32 indexed loanId)',
  'event LoanAdminClosed(bytes32 indexed loanId)',
] as const;

// AXIOMCreditMarket — permissioned LP pool (ERC-3643 identity-gated, AXUSD custody)
export const CREDIT_MARKET_ABI = [
  'function depositLiquidity(uint256 amountUsd) external',
  'function withdrawLiquidity(uint256 sharesToBurn) external',
  'function commitLiquidity(bytes32 loanId, uint256 amountUsd) external',
  'function disburseLoan(bytes32 loanId, address borrower, uint256 amount) external',
  'function receiveRepayment(bytes32 loanId, uint256 principalReturned, uint256 interestAmount) external',
  'function claimInterest() external',
  'function setReserveRatio(uint256 newBps) external',
  'function setFixedLoan(address fixedLoan) external',
  'function availableLiquidity() view returns (uint256)',
  'function totalPoolValue() view returns (uint256)',
  'function sharePrice() view returns (uint256)',
  'function pendingInterest(address lp) view returns (uint256)',
  'function isLpVerified(address lp) view returns (bool)',
  'function lpShares(address) view returns (uint256)',
  'function totalLpShares() view returns (uint256)',
  'function totalDeposited() view returns (uint256)',
  'function totalInterestReceived() view returns (uint256)',
  'function loanCommitment(bytes32) view returns (uint256)',
  'function reserveRatioBps() view returns (uint256)',
  'function fixedLoan() view returns (address)',
  'function identityRegistry() view returns (address)',
  'event LiquidityDeposited(address indexed lp, uint256 amountUsd, uint256 sharesIssued)',
  'event LiquidityWithdrawn(address indexed lp, uint256 axusdOut, uint256 sharesBurned)',
  'event LiquidityCommitted(bytes32 indexed loanId, uint256 amount)',
  'event LoanDisbursed(bytes32 indexed loanId, address indexed borrower, uint256 amount)',
  'event RepaymentReceived(bytes32 indexed loanId, uint256 principalReturned, uint256 interestReceived)',
  'event InterestClaimed(address indexed lp, uint256 amount)',
] as const;
