/**
 * AXIOM Credit Market — Deployed Contract Addresses
 * Generated by scripts/deploy-credit-market.ts
 * Deployed: 2026-03-22 on Arbitrum One (chainId: 42161)
 *
 * Verification:
 *   AXIOMFixedLoan:    https://arbitrum.blockscout.com/address/0xc40a4433706C82Dbc51Dc4dcfEf9ef51235349E9#code
 *   AXIOMCreditMarket: https://arbitrum.blockscout.com/address/0xE9d74BB7ffC09D2a63a35D7d3F85976659Fe388D#code
 */

export const CREDIT_MARKET_DEPLOYMENT = {
  network:           'Arbitrum One',
  chainId:           42161,
  deployedAt:        '2026-03-22',
  deployer:          '0x8d7892CF226B43d48B6e3ce988A1274e6D114C96',

  axusd:             '0x73585df5E62a5E85E6dd6b1df3C08E00eee5b89C',
  creditMarket:      '0xE9d74BB7ffC09D2a63a35D7d3F85976659Fe388D',
  fixedLoanNFT:      '0xc40a4433706C82Dbc51Dc4dcfEf9ef51235349E9',

  explorerBase:      'https://arbitrum.blockscout.com',
  wireTx:            '0x436b48ecfe5d8d54e79ad69b33e7874b1946df392463a2d914b678ec7c27197c',

  roles: {
    operatorRole:    '0x97667070c54ef182b0f5858b034beac1b6f3089aa2d3188bb1e8929f4fa9b929',
    minterRole:      '0x9f2df0fed2c77648de5860a4cc508cd0818c85b8b8a1ab4ceeef8d981c8956a6',
    adminRole:       '0x0000000000000000000000000000000000000000000000000000000000000000',
  },

  loanStatusMap: {
    0: 'PENDING',
    1: 'APPROVED',
    2: 'ACTIVE',
    3: 'DELINQUENT',
    4: 'REPAID',
    5: 'DEFAULTED',
  } as Record<number, string>,
} as const;

export const CREDIT_MARKET_ABI = [
  'function originateLoan(bytes32 loanId, address borrower, uint256 principal, uint256 rateBps, uint256 feeBps, uint256 termDays, string calldata propAddress) external',
  'function approveLoan(bytes32 loanId) external',
  'function fundLoan(bytes32 loanId) external',
  'function markDelinquent(bytes32 loanId) external',
  'function cureDelinquent(bytes32 loanId) external',
  'function defaultLoan(bytes32 loanId) external',
  'function closeLoan(bytes32 loanId) external',
  'function repayLoan(bytes32 loanId, uint256 paymentUsd6) external',
  'function depositLiquidity(uint256 amountUsd6) external',
  'function withdrawLiquidity(uint256 sharesToBurn) external',
  'function addLpAllowlist(address lp) external',
  'function removeLpAllowlist(address lp) external',
  'function isLpAllowed(address lp) view returns (bool)',
  'function getLoan(bytes32 loanId) view returns (tuple(bytes32 loanId, address borrower, uint256 principalUsd6, uint256 interestRateBps, uint256 originationFeeUsd6, uint256 termSeconds, uint8 status, uint256 fundedAt, uint256 dueAt, uint256 lastAccrualAt, uint256 totalRepaidUsd6, uint256 totalInterestPaidUsd6, string propertyAddress))',
  'function accruedInterest(bytes32 loanId) view returns (uint256)',
  'function totalDeposited() view returns (uint256)',
  'function totalDeployed() view returns (uint256)',
  'function totalWithdrawn() view returns (uint256)',
  'function lpShares(address) view returns (uint256)',
  'function totalLpShares() view returns (uint256)',
  'function availableLiquidity() view returns (uint256)',
  'function fixedLoanNFT() view returns (address)',
  'event LoanOriginated(bytes32 indexed loanId, address indexed borrower, uint256 principalUsd6, string propertyAddress)',
  'event LoanApproved(bytes32 indexed loanId)',
  'event LoanFunded(bytes32 indexed loanId, address indexed borrower, uint256 principalUsd6)',
  'event LoanRepayment(bytes32 indexed loanId, address indexed payer, uint256 paymentUsd6, uint256 interestPortion, uint256 principalPortion, uint256 remainingPrincipal)',
  'event LoanRepaid(bytes32 indexed loanId)',
  'event LoanDelinquent(bytes32 indexed loanId)',
  'event LoanCured(bytes32 indexed loanId)',
  'event LoanDefaulted(bytes32 indexed loanId)',
] as const;

export const FIXED_LOAN_ABI = [
  'function mintReceipt(bytes32 loanId, address borrower, uint256 principalUsd6, uint256 rateBps, uint256 termDays, uint256 dueAt, string calldata propAddress) external returns (uint256)',
  'function burnReceipt(bytes32 loanId) external',
  'function loanIdToTokenId(bytes32 loanId) view returns (uint256)',
  'function tokenURI(uint256 tokenId) view returns (string)',
  'function ownerOf(uint256 tokenId) view returns (address)',
] as const;
