import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

interface CaseData {
  id: number;
  case_title: string;
  ancestor_primary_name: string;
  jurisdiction_code: string;
  status: string;
  created_at: string;
}

interface Person {
  id: number;
  full_name: string;
  birth_year?: string;
  birth_place?: string;
  death_year?: string;
  death_place?: string;
  is_primary_ancestor: boolean;
}

interface SavedRecord {
  id: number;
  record_name: string;
  record_type: string;
  source: string;
  confidence: string;
  is_land_record: boolean;
  details: string;
}

interface Note {
  id: number;
  title: string;
  content: string;
  created_at: string;
}

export default function ReportPage() {
  const router = useRouter();
  const { id } = router.query;

  const [caseData, setCaseData] = useState<CaseData | null>(null);
  const [persons, setPersons] = useState<Person[]>([]);
  const [records, setRecords] = useState<SavedRecord[]>([]);
  const [notes, setNotes] = useState<Note[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const [includePersons, setIncludePersons] = useState(true);
  const [includeRecords, setIncludeRecords] = useState(true);
  const [includeNotes, setIncludeNotes] = useState(true);
  const [includeLandRecordsOnly, setIncludeLandRecordsOnly] = useState(false);

  useEffect(() => {
    if (!id) return;

    const fetchData = async () => {
      try {
        const [caseRes, treeRes, recordsRes, notesRes] = await Promise.all([
          fetch(`/api/workbook/cases/${id}`),
          fetch(`/api/workbook/family-tree/persons?caseId=${id}`),
          fetch(`/api/workbook/saved-records?caseId=${id}`),
          fetch(`/api/workbook/notes?caseId=${id}`),
        ]);

        const [caseJson, treeJson, recordsJson, notesJson] = await Promise.all([
          caseRes.json(),
          treeRes.json(),
          recordsRes.json(),
          notesRes.json(),
        ]);

        setCaseData(caseJson.data);
        setPersons(treeJson.persons || []);
        setRecords(recordsJson.records || []);
        setNotes(notesJson.notes || []);
      } catch (err) {
        console.error('Failed to load data:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [id]);

  const generateReport = () => {
    if (!caseData) return;

    setGenerating(true);

    const filteredRecords = includeLandRecordsOnly 
      ? records.filter(r => r.is_land_record) 
      : records;

    let reportContent = `
HEIR PROPERTY RESEARCH REPORT
=============================

Case: ${caseData.case_title}
Primary Ancestor: ${caseData.ancestor_primary_name}
Jurisdiction: ${caseData.jurisdiction_code || 'Not specified'}
Report Generated: ${new Date().toLocaleDateString()}
Status: ${caseData.status}

`;

    if (includePersons && persons.length > 0) {
      reportContent += `
FAMILY MEMBERS
--------------
`;
      persons.forEach((person, i) => {
        reportContent += `
${i + 1}. ${person.full_name}${person.is_primary_ancestor ? ' (Primary Ancestor)' : ''}
   Birth: ${person.birth_year || 'Unknown'}${person.birth_place ? `, ${person.birth_place}` : ''}
   Death: ${person.death_year || 'Unknown'}${person.death_place ? `, ${person.death_place}` : ''}
`;
      });
    }

    if (includeRecords && filteredRecords.length > 0) {
      reportContent += `

SAVED RECORDS
-------------
`;
      filteredRecords.forEach((record, i) => {
        reportContent += `
${i + 1}. ${record.record_name}
   Type: ${record.record_type}
   Source: ${record.source}
   Confidence: ${record.confidence}
   ${record.is_land_record ? '[LAND RECORD]' : ''}
   Details: ${record.details || 'N/A'}
`;
      });
    }

    if (includeNotes && notes.length > 0) {
      reportContent += `

RESEARCH NOTES
--------------
`;
      notes.forEach((note, i) => {
        reportContent += `
${i + 1}. ${note.title}
   Date: ${new Date(note.created_at).toLocaleDateString()}
   ${note.content}
`;
      });
    }

    reportContent += `

=============================
END OF REPORT

This report was generated by the Land Reclamation Workbook.
For legal purposes, verify all information with official records.
`;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${caseData.case_title.replace(/\s+/g, '_')}_Research_Report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setGenerating(false);
  };

  const printReport = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-amber-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  const landRecords = records.filter(r => r.is_land_record);

  return (
    <>
      <Head>
        <title>Export Report | Land Reclamation Workbook</title>
      </Head>

      <style jsx global>{`
        @media print {
          .no-print { display: none !important; }
          .print-only { display: block !important; }
          body { background: white; }
        }
      `}</style>

      <div className="min-h-screen bg-gray-50">
        <header className="bg-gradient-to-r from-amber-600 to-orange-600 text-white no-print">
          <div className="max-w-4xl mx-auto px-4 py-6">
            <Link href={`/workbook/case/${id}`} className="text-amber-100 hover:text-white text-sm mb-2 inline-block">
              ← Back to Case
            </Link>
            <h1 className="text-2xl font-bold">Export Research Report</h1>
            <p className="text-amber-100 mt-1">Generate a professional heir property research report</p>
          </div>
        </header>

        <main className="max-w-4xl mx-auto px-4 py-8">
          <div className="grid md:grid-cols-3 gap-6">
            <div className="md:col-span-1 no-print">
              <div className="bg-white rounded-xl border p-6 sticky top-4">
                <h2 className="font-semibold text-gray-900 mb-4">Report Options</h2>

                <div className="space-y-4">
                  <div className="p-3 bg-gray-50 rounded-lg">
                    <h3 className="text-sm font-medium text-gray-700 mb-2">Include Sections</h3>
                    <div className="space-y-2">
                      <label className="flex items-center gap-2 text-sm">
                        <input
                          type="checkbox"
                          checked={includePersons}
                          onChange={(e) => setIncludePersons(e.target.checked)}
                          className="rounded text-amber-500"
                        />
                        Family Members ({persons.length})
                      </label>
                      <label className="flex items-center gap-2 text-sm">
                        <input
                          type="checkbox"
                          checked={includeRecords}
                          onChange={(e) => setIncludeRecords(e.target.checked)}
                          className="rounded text-amber-500"
                        />
                        Saved Records ({records.length})
                      </label>
                      {includeRecords && (
                        <label className="flex items-center gap-2 text-sm ml-5">
                          <input
                            type="checkbox"
                            checked={includeLandRecordsOnly}
                            onChange={(e) => setIncludeLandRecordsOnly(e.target.checked)}
                            className="rounded text-blue-500"
                          />
                          Land records only ({landRecords.length})
                        </label>
                      )}
                      <label className="flex items-center gap-2 text-sm">
                        <input
                          type="checkbox"
                          checked={includeNotes}
                          onChange={(e) => setIncludeNotes(e.target.checked)}
                          className="rounded text-amber-500"
                        />
                        Research Notes ({notes.length})
                      </label>
                    </div>
                  </div>

                  <button
                    onClick={printReport}
                    className="w-full py-3 bg-amber-500 text-white rounded-lg font-medium hover:bg-amber-600 transition"
                  >
                    Save as PDF / Print
                  </button>
                  <p className="text-xs text-gray-500 text-center">
                    Use your browser's "Save as PDF" option in the print dialog
                  </p>

                  <button
                    onClick={generateReport}
                    disabled={generating}
                    className="w-full py-3 border border-gray-300 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition disabled:opacity-50"
                  >
                    {generating ? 'Generating...' : 'Download Text Report'}
                  </button>
                </div>
              </div>
            </div>

            <div className="md:col-span-2">
              <div className="bg-white rounded-xl border p-8 shadow-sm" id="report-preview">
                <div className="text-center border-b pb-6 mb-6">
                  <h1 className="text-2xl font-bold text-gray-900">Heir Property Research Report</h1>
                  <p className="text-gray-600 mt-2">{caseData?.case_title}</p>
                </div>

                <div className="grid grid-cols-2 gap-4 mb-8 text-sm">
                  <div>
                    <span className="text-gray-500">Primary Ancestor:</span>
                    <p className="font-medium">{caseData?.ancestor_primary_name}</p>
                  </div>
                  <div>
                    <span className="text-gray-500">Jurisdiction:</span>
                    <p className="font-medium">{caseData?.jurisdiction_code || 'Not specified'}</p>
                  </div>
                  <div>
                    <span className="text-gray-500">Report Date:</span>
                    <p className="font-medium">{new Date().toLocaleDateString()}</p>
                  </div>
                  <div>
                    <span className="text-gray-500">Case Status:</span>
                    <p className="font-medium capitalize">{caseData?.status}</p>
                  </div>
                </div>

                <div className="grid grid-cols-4 gap-4 mb-8">
                  <div className="text-center p-4 bg-green-50 rounded-lg">
                    <div className="text-2xl font-bold text-green-600">{persons.length}</div>
                    <div className="text-xs text-green-700">Family Members</div>
                  </div>
                  <div className="text-center p-4 bg-blue-50 rounded-lg">
                    <div className="text-2xl font-bold text-blue-600">{records.length}</div>
                    <div className="text-xs text-blue-700">Records</div>
                  </div>
                  <div className="text-center p-4 bg-purple-50 rounded-lg">
                    <div className="text-2xl font-bold text-purple-600">{landRecords.length}</div>
                    <div className="text-xs text-purple-700">Land Records</div>
                  </div>
                  <div className="text-center p-4 bg-amber-50 rounded-lg">
                    <div className="text-2xl font-bold text-amber-600">{notes.length}</div>
                    <div className="text-xs text-amber-700">Notes</div>
                  </div>
                </div>

                {includePersons && persons.length > 0 && (
                  <div className="mb-8">
                    <h2 className="text-lg font-semibold text-gray-900 mb-4 border-b pb-2">Family Members</h2>
                    <div className="space-y-3">
                      {persons.map(person => (
                        <div key={person.id} className="flex items-start gap-3 text-sm">
                          <span className="text-green-500">●</span>
                          <div>
                            <span className="font-medium">{person.full_name}</span>
                            {person.is_primary_ancestor && (
                              <span className="ml-2 px-2 py-0.5 bg-amber-100 text-amber-700 text-xs rounded">Primary</span>
                            )}
                            <div className="text-gray-500 text-xs">
                              {person.birth_year && `b. ${person.birth_year}`}
                              {person.birth_year && person.death_year && ' - '}
                              {person.death_year && `d. ${person.death_year}`}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {includeRecords && (includeLandRecordsOnly ? landRecords : records).length > 0 && (
                  <div className="mb-8">
                    <h2 className="text-lg font-semibold text-gray-900 mb-4 border-b pb-2">
                      {includeLandRecordsOnly ? 'Land Records' : 'Saved Records'}
                    </h2>
                    <div className="space-y-3">
                      {(includeLandRecordsOnly ? landRecords : records).map(record => (
                        <div key={record.id} className="p-3 bg-gray-50 rounded-lg text-sm">
                          <div className="flex items-start justify-between">
                            <span className="font-medium">{record.record_name}</span>
                            <span className={`px-2 py-0.5 text-xs rounded ${
                              record.confidence === 'high' ? 'bg-green-100 text-green-700' :
                              record.confidence === 'medium' ? 'bg-yellow-100 text-yellow-700' :
                              'bg-red-100 text-red-700'
                            }`}>
                              {record.confidence}
                            </span>
                          </div>
                          <div className="text-gray-500 text-xs mt-1">
                            {record.record_type} • {record.source}
                          </div>
                          {record.details && (
                            <p className="text-gray-600 mt-2 text-xs">{record.details}</p>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {includeNotes && notes.length > 0 && (
                  <div className="mb-8">
                    <h2 className="text-lg font-semibold text-gray-900 mb-4 border-b pb-2">Research Notes</h2>
                    <div className="space-y-3">
                      {notes.map(note => (
                        <div key={note.id} className="p-3 bg-amber-50 rounded-lg text-sm">
                          <div className="font-medium">{note.title}</div>
                          <div className="text-gray-500 text-xs mb-2">
                            {new Date(note.created_at).toLocaleDateString()}
                          </div>
                          <p className="text-gray-700 whitespace-pre-wrap">{note.content}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <div className="text-center text-xs text-gray-400 border-t pt-4 mt-8">
                  Generated by Land Reclamation Workbook • For legal purposes, verify all information with official records
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
