[package]
name = "axiom_sui"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.72.1" }

[addresses]
axiom_sui = "0x0"
