/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IIdentityRegistryInterface extends Interface {
    getFunction(nameOrSignature: "addAgent" | "contains" | "deleteIdentity" | "identity" | "investorCountry" | "isAgent" | "isVerified" | "registerIdentity" | "removeAgent" | "updateCountry" | "updateIdentity"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentAdded" | "AgentRemoved" | "CountryUpdated" | "IdentityRegistered" | "IdentityRemoved" | "IdentityUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'addAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'contains', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deleteIdentity', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'identity', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'investorCountry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isVerified', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerIdentity', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeAgent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateCountry', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateIdentity', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contains', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deleteIdentity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'identity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'investorCountry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isVerified', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerIdentity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCountry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateIdentity', data: BytesLike): Result;
  }

  
    export namespace AgentAddedEvent {
      export type InputTuple = [agent: AddressLike];
      export type OutputTuple = [agent: string];
      export interface OutputObject {agent: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentRemovedEvent {
      export type InputTuple = [agent: AddressLike];
      export type OutputTuple = [agent: string];
      export interface OutputObject {agent: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CountryUpdatedEvent {
      export type InputTuple = [userAddress: AddressLike, country: BigNumberish];
      export type OutputTuple = [userAddress: string, country: bigint];
      export interface OutputObject {userAddress: string, country: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityRegisteredEvent {
      export type InputTuple = [userAddress: AddressLike, identity: AddressLike];
      export type OutputTuple = [userAddress: string, identity: string];
      export interface OutputObject {userAddress: string, identity: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityRemovedEvent {
      export type InputTuple = [userAddress: AddressLike];
      export type OutputTuple = [userAddress: string];
      export interface OutputObject {userAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IdentityUpdatedEvent {
      export type InputTuple = [userAddress: AddressLike, newIdentity: AddressLike];
      export type OutputTuple = [userAddress: string, newIdentity: string];
      export interface OutputObject {userAddress: string, newIdentity: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IIdentityRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IIdentityRegistry;
    waitForDeployment(): Promise<this>;

    interface: IIdentityRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addAgent: TypedContractMethod<
      [_agent: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    contains: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    deleteIdentity: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    identity: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [string],
      'view'
    >
    

    
    investorCountry: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    isAgent: TypedContractMethod<
      [_agent: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isVerified: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    registerIdentity: TypedContractMethod<
      [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    removeAgent: TypedContractMethod<
      [_agent: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateCountry: TypedContractMethod<
      [_userAddress: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateIdentity: TypedContractMethod<
      [_userAddress: AddressLike, _identity: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addAgent'): TypedContractMethod<
      [_agent: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contains'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deleteIdentity'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'identity'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'investorCountry'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isAgent'): TypedContractMethod<
      [_agent: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isVerified'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerIdentity'): TypedContractMethod<
      [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeAgent'): TypedContractMethod<
      [_agent: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCountry'): TypedContractMethod<
      [_userAddress: AddressLike, _country: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateIdentity'): TypedContractMethod<
      [_userAddress: AddressLike, _identity: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentAdded'): TypedContractEvent<AgentAddedEvent.InputTuple, AgentAddedEvent.OutputTuple, AgentAddedEvent.OutputObject>;
getEvent(key: 'AgentRemoved'): TypedContractEvent<AgentRemovedEvent.InputTuple, AgentRemovedEvent.OutputTuple, AgentRemovedEvent.OutputObject>;
getEvent(key: 'CountryUpdated'): TypedContractEvent<CountryUpdatedEvent.InputTuple, CountryUpdatedEvent.OutputTuple, CountryUpdatedEvent.OutputObject>;
getEvent(key: 'IdentityRegistered'): TypedContractEvent<IdentityRegisteredEvent.InputTuple, IdentityRegisteredEvent.OutputTuple, IdentityRegisteredEvent.OutputObject>;
getEvent(key: 'IdentityRemoved'): TypedContractEvent<IdentityRemovedEvent.InputTuple, IdentityRemovedEvent.OutputTuple, IdentityRemovedEvent.OutputObject>;
getEvent(key: 'IdentityUpdated'): TypedContractEvent<IdentityUpdatedEvent.InputTuple, IdentityUpdatedEvent.OutputTuple, IdentityUpdatedEvent.OutputObject>;

    filters: {
      
      'AgentAdded(address)': TypedContractEvent<AgentAddedEvent.InputTuple, AgentAddedEvent.OutputTuple, AgentAddedEvent.OutputObject>;
      AgentAdded: TypedContractEvent<AgentAddedEvent.InputTuple, AgentAddedEvent.OutputTuple, AgentAddedEvent.OutputObject>;
    

      'AgentRemoved(address)': TypedContractEvent<AgentRemovedEvent.InputTuple, AgentRemovedEvent.OutputTuple, AgentRemovedEvent.OutputObject>;
      AgentRemoved: TypedContractEvent<AgentRemovedEvent.InputTuple, AgentRemovedEvent.OutputTuple, AgentRemovedEvent.OutputObject>;
    

      'CountryUpdated(address,uint16)': TypedContractEvent<CountryUpdatedEvent.InputTuple, CountryUpdatedEvent.OutputTuple, CountryUpdatedEvent.OutputObject>;
      CountryUpdated: TypedContractEvent<CountryUpdatedEvent.InputTuple, CountryUpdatedEvent.OutputTuple, CountryUpdatedEvent.OutputObject>;
    

      'IdentityRegistered(address,address)': TypedContractEvent<IdentityRegisteredEvent.InputTuple, IdentityRegisteredEvent.OutputTuple, IdentityRegisteredEvent.OutputObject>;
      IdentityRegistered: TypedContractEvent<IdentityRegisteredEvent.InputTuple, IdentityRegisteredEvent.OutputTuple, IdentityRegisteredEvent.OutputObject>;
    

      'IdentityRemoved(address)': TypedContractEvent<IdentityRemovedEvent.InputTuple, IdentityRemovedEvent.OutputTuple, IdentityRemovedEvent.OutputObject>;
      IdentityRemoved: TypedContractEvent<IdentityRemovedEvent.InputTuple, IdentityRemovedEvent.OutputTuple, IdentityRemovedEvent.OutputObject>;
    

      'IdentityUpdated(address,address)': TypedContractEvent<IdentityUpdatedEvent.InputTuple, IdentityUpdatedEvent.OutputTuple, IdentityUpdatedEvent.OutputObject>;
      IdentityUpdated: TypedContractEvent<IdentityUpdatedEvent.InputTuple, IdentityUpdatedEvent.OutputTuple, IdentityUpdatedEvent.OutputObject>;
    
    };
  }