/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IModuleInterface extends Interface {
    getFunction(nameOrSignature: "bindCompliance" | "isComplianceBound" | "moduleBurnAction" | "moduleCheck" | "moduleMintAction" | "moduleTransferAction" | "name" | "unbindCompliance"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'bindCompliance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isComplianceBound', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleBurnAction', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleCheck', values: [AddressLike, AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleMintAction', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'moduleTransferAction', values: [AddressLike, AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'unbindCompliance', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'bindCompliance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isComplianceBound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleBurnAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleMintAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moduleTransferAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbindCompliance', data: BytesLike): Result;
  }

  

  export interface IModule extends BaseContract {
    
    connect(runner?: ContractRunner | null): IModule;
    waitForDeployment(): Promise<this>;

    interface: IModuleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bindCompliance: TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isComplianceBound: TypedContractMethod<
      [_compliance: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    moduleBurnAction: TypedContractMethod<
      [_from: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    moduleCheck: TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    moduleMintAction: TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    moduleTransferAction: TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unbindCompliance: TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bindCompliance'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isComplianceBound'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'moduleBurnAction'): TypedContractMethod<
      [_from: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'moduleCheck'): TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'moduleMintAction'): TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'moduleTransferAction'): TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _value: BigNumberish, _compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unbindCompliance'): TypedContractMethod<
      [_compliance: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }