/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIdentityRegistry } from './IIdentityRegistry.js';
export type { IModularCompliance } from './IModularCompliance.js';
export type { IModule } from './IModule.js';