import { pgTable, serial, varchar, text, timestamp, boolean, integer, numeric } from 'drizzle-orm/pg-core';

export const lfAccreditationRecords = pgTable("lf_accreditation_records", {
  id: serial("id").primaryKey(),
  walletAddress: varchar("wallet_address", { length: 42 }),
  email: varchar("email", { length: 255 }),
  fullName: varchar("full_name", { length: 200 }),
  method: varchar("method", { length: 50 }).notNull(),
  incomeThreshold: varchar("income_threshold", { length: 50 }),
  netWorthThreshold: varchar("net_worth_threshold", { length: 50 }),
  entityAssetsThreshold: varchar("entity_assets_threshold", { length: 50 }),
  professionalCertification: varchar("professional_certification", { length: 100 }),
  filingStatus: varchar("filing_status", { length: 50 }),
  selfCertified: boolean("self_certified").default(false),
  selfCertificationStatement: text("self_certification_statement"),
  verificationStatus: varchar("verification_status", { length: 50 }).default('pending'),
  adminReviewedBy: varchar("admin_reviewed_by", { length: 200 }),
  adminNotes: text("admin_notes"),
  expiresAt: timestamp("expires_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  reviewedAt: timestamp("reviewed_at"),
});

export const loanApplications = pgTable("loan_applications", {
  id: serial("id").primaryKey(),
  borrowerName: varchar("borrower_name", { length: 200 }).notNull(),
  borrowerEmail: varchar("borrower_email", { length: 255 }).notNull(),
  borrowerPhone: varchar("borrower_phone", { length: 20 }),
  companyName: varchar("company_name", { length: 255 }),
  borrowerAddress: varchar("borrower_address", { length: 500 }),
  yearsExperience: integer("years_experience"),
  projectsCompleted: integer("projects_completed"),
  propertyAddress: varchar("property_address", { length: 500 }).notNull(),
  propertyCity: varchar("property_city", { length: 100 }),
  propertyState: varchar("property_state", { length: 50 }),
  propertyZip: varchar("property_zip", { length: 20 }),
  propertyType: varchar("property_type", { length: 50 }),
  purchasePrice: varchar("purchase_price", { length: 50 }),
  rehabBudget: varchar("rehab_budget", { length: 50 }),
  arvEstimate: varchar("arv_estimate", { length: 50 }),
  loanAmountRequested: varchar("loan_amount_requested", { length: 50 }).notNull(),
  loanTermMonths: integer("loan_term_months"),
  acquisitionStatus: varchar("acquisition_status", { length: 50 }),
  rehabScope: text("rehab_scope"),
  exitStrategy: varchar("exit_strategy", { length: 50 }),
  timelineMonths: integer("timeline_months"),
  hasContractor: boolean("has_contractor"),
  contractorName: varchar("contractor_name", { length: 200 }),
  additionalNotes: text("additional_notes"),
  status: varchar("status", { length: 50 }),
  adminNotes: text("admin_notes"),
  rejectionReason: text("rejection_reason"),
  walletAddress: varchar("wallet_address", { length: 42 }),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
  reviewedAt: timestamp("reviewed_at"),
  approvedAt: timestamp("approved_at"),
  fundedAt: timestamp("funded_at"),
});
