/**
 * Deploy: AXIOMFixedLoan + AXIOMCreditMarket
 * Network: Arbitrum One
 * Run: npx hardhat run scripts/deploy-credit-market.ts --network arbitrum
 *
 * Reads AXUSD address from src/config/activeContracts.generated.ts
 * Writes deployment output to src/config/creditMarket.generated.ts
 */
import { ethers, run } from "hardhat";
import * as fs from "fs";
import * as path from "path";

// Read AXUSD from canonical source
import { ACTIVE_AXUSD } from "../src/config/activeContracts.generated";

async function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function verifyContract(address: string, args: unknown[]) {
  console.log(`\n   Verifying ${address}...`);
  try {
    await run("verify:verify", { address, constructorArguments: args });
    console.log(`   ✓ Verified`);
  } catch (err: unknown) {
    const e = err as { message?: string };
    if (e?.message?.includes("Already Verified") || e?.message?.includes("already verified")) {
      console.log(`   ✓ Already verified`);
    } else {
      console.warn(`   ⚠ Verification skipped: ${e?.message ?? err}`);
    }
  }
}

function writeGeneratedConfig(params: {
  deployer: string;
  axusd: string;
  creditMarket: string;
  fixedLoanNFT: string;
  chainId: bigint;
  wireTx: string;
  deployedAt: string;
}) {
  const operatorRole = ethers.keccak256(ethers.toUtf8Bytes("OPERATOR_ROLE"));
  const minterRole   = ethers.keccak256(ethers.toUtf8Bytes("MINTER_ROLE"));

  const content = `/**
 * AXIOM Credit Market — Deployed Contract Addresses
 * Generated by scripts/deploy-credit-market.ts
 * Deployed: ${params.deployedAt} on Arbitrum One (chainId: ${params.chainId})
 *
 * Verification:
 *   AXIOMFixedLoan:    https://arbitrum.blockscout.com/address/${params.fixedLoanNFT}#code
 *   AXIOMCreditMarket: https://arbitrum.blockscout.com/address/${params.creditMarket}#code
 */

export const CREDIT_MARKET_DEPLOYMENT = {
  network:           'Arbitrum One',
  chainId:           ${params.chainId},
  deployedAt:        '${params.deployedAt}',
  deployer:          '${params.deployer}',

  axusd:             '${params.axusd}',
  creditMarket:      '${params.creditMarket}',
  fixedLoanNFT:      '${params.fixedLoanNFT}',

  explorerBase:      'https://arbitrum.blockscout.com',
  wireTx:            '${params.wireTx}',

  roles: {
    operatorRole:    '${operatorRole}',
    minterRole:      '${minterRole}',
    adminRole:       '0x0000000000000000000000000000000000000000000000000000000000000000',
  },

  loanStatusMap: {
    0: 'PENDING',
    1: 'APPROVED',
    2: 'ACTIVE',
    3: 'DELINQUENT',
    4: 'REPAID',
    5: 'DEFAULTED',
  } as Record<number, string>,
} as const;

export const CREDIT_MARKET_ABI = [
  'function originateLoan(bytes32 loanId, address borrower, uint256 principal, uint256 rateBps, uint256 feeBps, uint256 termDays, string calldata propAddress) external',
  'function approveLoan(bytes32 loanId) external',
  'function fundLoan(bytes32 loanId) external',
  'function markDelinquent(bytes32 loanId) external',
  'function cureDelinquent(bytes32 loanId) external',
  'function defaultLoan(bytes32 loanId) external',
  'function repayLoan(bytes32 loanId, uint256 paymentUsd6) external',
  'function depositLiquidity(uint256 amountUsd6) external',
  'function withdrawLiquidity(uint256 sharesToBurn) external',
  'function addLpAllowlist(address lp) external',
  'function removeLpAllowlist(address lp) external',
  'function isLpAllowed(address lp) view returns (bool)',
  'function getLoan(bytes32 loanId) view returns (tuple(bytes32 loanId, address borrower, uint256 principalUsd6, uint256 interestRateBps, uint256 originationFeeUsd6, uint256 termSeconds, uint8 status, uint256 fundedAt, uint256 dueAt, uint256 lastAccrualAt, uint256 totalRepaidUsd6, uint256 totalInterestPaidUsd6, string propertyAddress))',
  'function accruedInterest(bytes32 loanId) view returns (uint256)',
  'function totalDeposited() view returns (uint256)',
  'function totalDeployed() view returns (uint256)',
  'function totalWithdrawn() view returns (uint256)',
  'function lpShares(address) view returns (uint256)',
  'function totalLpShares() view returns (uint256)',
  'function availableLiquidity() view returns (uint256)',
  'function fixedLoanNFT() view returns (address)',
  'event LoanOriginated(bytes32 indexed loanId, address indexed borrower, uint256 principalUsd6, string propertyAddress)',
  'event LoanApproved(bytes32 indexed loanId)',
  'event LoanFunded(bytes32 indexed loanId, address indexed borrower, uint256 principalUsd6)',
  'event LoanRepayment(bytes32 indexed loanId, address indexed payer, uint256 paymentUsd6, uint256 interestPortion, uint256 principalPortion, uint256 remainingPrincipal)',
  'event LoanRepaid(bytes32 indexed loanId)',
  'event LoanDelinquent(bytes32 indexed loanId)',
  'event LoanCured(bytes32 indexed loanId)',
  'event LoanDefaulted(bytes32 indexed loanId)',
] as const;

export const FIXED_LOAN_ABI = [
  'function mintReceipt(bytes32 loanId, address borrower, uint256 principalUsd6, uint256 rateBps, uint256 termDays, uint256 dueAt, string calldata propAddress) external returns (uint256)',
  'function burnReceipt(bytes32 loanId) external',
  'function loanIdToTokenId(bytes32 loanId) view returns (uint256)',
  'function tokenURI(uint256 tokenId) view returns (string)',
  'function ownerOf(uint256 tokenId) view returns (address)',
] as const;
`;

  const outPath = path.join(__dirname, "../src/config/creditMarket.generated.ts");
  fs.writeFileSync(outPath, content, "utf8");
  console.log("   ✓ Wrote:", outPath);
}

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("═══════════════════════════════════════════════════════════════");
  console.log("  AXIOM CREDIT MARKET — DEPLOYMENT");
  console.log("  AXIOMFixedLoan (ERC-721) + AXIOMCreditMarket (Lending Vault)");
  console.log("═══════════════════════════════════════════════════════════════");
  console.log("\nDeployer:", deployer.address);
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Balance:", ethers.formatEther(balance), "ETH");
  console.log("AXUSD (from activeContracts.generated.ts):", ACTIVE_AXUSD);
  const network = await ethers.provider.getNetwork();
  console.log("Network ChainId:", network.chainId, "\n");

  if (network.chainId !== 42161n) {
    throw new Error(`Wrong network. Expected Arbitrum One (42161), got ${network.chainId}`);
  }
  if (balance < ethers.parseEther("0.002")) {
    throw new Error("Insufficient ETH balance for deployment (need ≥ 0.002 ETH)");
  }

  // ── 1. Deploy AXIOMFixedLoan ──────────────────────────────────────────
  console.log("[1/5] Deploying AXIOMFixedLoan...");
  const FixedLoanFactory = await ethers.getContractFactory("AXIOMFixedLoan");
  const fixedLoan = await FixedLoanFactory.deploy(deployer.address);
  await fixedLoan.waitForDeployment();
  const fixedLoanAddress = await fixedLoan.getAddress();
  console.log("   ✓ AXIOMFixedLoan:", fixedLoanAddress);
  await sleep(3000);

  // ── 2. Deploy AXIOMCreditMarket ───────────────────────────────────────
  console.log("\n[2/5] Deploying AXIOMCreditMarket...");
  const CreditMarketFactory = await ethers.getContractFactory("AXIOMCreditMarket");
  const creditMarket = await CreditMarketFactory.deploy(ACTIVE_AXUSD, deployer.address);
  await creditMarket.waitForDeployment();
  const creditMarketAddress = await creditMarket.getAddress();
  console.log("   ✓ AXIOMCreditMarket:", creditMarketAddress);
  await sleep(3000);

  // ── 3. Wire: grant MINTER_ROLE on FixedLoan to CreditMarket ──────────
  console.log("\n[3/5] Wiring contracts...");
  const MINTER_ROLE = ethers.keccak256(ethers.toUtf8Bytes("MINTER_ROLE"));
  const grantTx = await fixedLoan.grantRole(MINTER_ROLE, creditMarketAddress);
  await grantTx.wait();
  console.log("   ✓ MINTER_ROLE granted to CreditMarket on FixedLoan");

  const setNftTx = await creditMarket.setFixedLoanNFT(fixedLoanAddress);
  await setNftTx.wait();
  const wireTx = setNftTx.hash;
  console.log("   ✓ FixedLoanNFT set on CreditMarket, tx:", wireTx);
  await sleep(3000);

  // ── 4. Write generated config ─────────────────────────────────────────
  console.log("\n[4/5] Writing src/config/creditMarket.generated.ts...");
  const deployedAt = new Date().toISOString().slice(0, 10);
  writeGeneratedConfig({
    deployer: deployer.address,
    axusd: ACTIVE_AXUSD,
    creditMarket: creditMarketAddress,
    fixedLoanNFT: fixedLoanAddress,
    chainId: network.chainId,
    wireTx,
    deployedAt,
  });

  // ── 5. Print summary ──────────────────────────────────────────────────
  console.log("\n═══════════════════════════════════════════════════════════════");
  console.log("  DEPLOYMENT COMPLETE");
  console.log("═══════════════════════════════════════════════════════════════");
  console.log(`  AXIOMFixedLoan:    ${fixedLoanAddress}`);
  console.log(`  AXIOMCreditMarket: ${creditMarketAddress}`);
  console.log(`  AXUSD (vault):     ${ACTIVE_AXUSD}`);
  console.log(`  Wire tx:           ${wireTx}`);
  console.log("═══════════════════════════════════════════════════════════════\n");

  // ── 6. Verify on Arbiscan / Blockscout ────────────────────────────────
  console.log("[5/5] Verifying contracts on block explorer...");
  await sleep(10000);
  await verifyContract(fixedLoanAddress, [deployer.address]);
  await verifyContract(creditMarketAddress, [ACTIVE_AXUSD, deployer.address]);

  console.log("\nDeployment script complete.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
