/**
 * Deploy: AXIOMFixedLoan + AXIOMCreditMarket
 * Network: Arbitrum One
 * Run: npx hardhat run scripts/deploy-credit-market.ts --network arbitrum
 *
 * AXIOMFixedLoan: Fixed-term loan engine (draw schedule, amortized/interest-only, prepayment)
 * AXIOMCreditMarket: LP pool with ERC-3643 IdentityRegistry gating (Wildcat V2 pattern)
 *
 * Reads AXUSD address from src/config/activeContracts.generated.ts
 * Writes deployment output to src/config/creditMarket.generated.ts
 */
import { ethers, run } from "hardhat";
import * as fs from "fs";
import * as path from "path";

import { ACTIVE_AXUSD } from "../src/config/activeContracts.generated";

// Deployed ERC-3643 IdentityRegistry on Arbitrum One (from shared/contracts-3643.ts)
const IDENTITY_REGISTRY = "0x58f64a1262d5434d6C7637a2309b0999bB6D1970";

async function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function verifyContract(address: string, args: unknown[]) {
  console.log(`\n   Verifying ${address}...`);
  try {
    await run("verify:verify", { address, constructorArguments: args });
    console.log(`   ✓ Verified`);
  } catch (err: unknown) {
    const e = err as { message?: string };
    if (e?.message?.includes("Already Verified") || e?.message?.includes("already verified")) {
      console.log(`   ✓ Already verified`);
    } else {
      console.warn(`   ⚠ Verification skipped: ${e?.message ?? err}`);
    }
  }
}

function writeGeneratedConfig(params: {
  deployer: string;
  axusd: string;
  identityRegistry: string;
  creditMarket: string;
  fixedLoan: string;
  chainId: bigint;
  wireTx: string;
  deployedAt: string;
}) {
  const operatorRole = ethers.keccak256(ethers.toUtf8Bytes("OPERATOR_ROLE"));

  const content = `/**
 * AXIOM Credit Market v4 — Deployed Contract Addresses
 * Generated by scripts/deploy-credit-market.ts
 * Deployed: ${params.deployedAt} on Arbitrum One (chainId: ${params.chainId})
 *
 * AXIOMFixedLoan: Fixed-term loan engine (draw schedule, amortized/interest-only, prepayment)
 * AXIOMCreditMarket: Permissioned LP pool (ERC-3643 IdentityRegistry gating)
 *
 * Verification:
 *   AXIOMFixedLoan:    https://arbitrum.blockscout.com/address/${params.fixedLoan}#code
 *   AXIOMCreditMarket: https://arbitrum.blockscout.com/address/${params.creditMarket}#code
 */

export const CREDIT_MARKET_DEPLOYMENT = {
  network:           'Arbitrum One',
  chainId:           ${params.chainId},
  deployedAt:        '${params.deployedAt}',
  deployer:          '${params.deployer}',

  axusd:             '${params.axusd}',
  identityRegistry:  '${params.identityRegistry}',
  creditMarket:      '${params.creditMarket}',
  fixedLoan:         '${params.fixedLoan}',

  explorerBase:      'https://arbitrum.blockscout.com',
  wireTx:            '${params.wireTx}',

  roles: {
    operatorRole:    '${operatorRole}',
    adminRole:       '0x0000000000000000000000000000000000000000000000000000000000000000',
  },

  loanStatusMap: {
    0: 'PENDING',
    1: 'APPROVED',
    2: 'ACTIVE',
    3: 'DELINQUENT',
    4: 'DEFAULTED',
    5: 'REPAID',
  } as Record<number, string>,

  paymentModes: {
    0: 'AMORTIZED',
    1: 'INTEREST_ONLY',
  } as Record<number, string>,
} as const;

// AXIOMFixedLoan — fixed-term loan engine
export const FIXED_LOAN_ABI = [
  'function originateLoan(bytes32 loanId, address borrower, uint8 paymentMode, uint256 rateBps, uint256 prepayBps, uint256 graceSecs, uint256 termSecs, string calldata propAddress, uint256[] calldata tranchAmts, uint256[] calldata tranchRelease) external',
  'function approveLoan(bytes32 loanId) external',
  'function disburseTranche(bytes32 loanId, uint8 trancheIndex) external',
  'function repayLoan(bytes32 loanId, uint256 paymentAmt) external',
  'function prepayLoan(bytes32 loanId) external',
  'function markDelinquent(bytes32 loanId) external',
  'function cureDelinquent(bytes32 loanId) external',
  'function defaultLoan(bytes32 loanId) external',
  'function closeLoan(bytes32 loanId) external',
  'function getLoan(bytes32 loanId) view returns (tuple(bytes32 loanId, address borrower, uint8 paymentMode, uint256 interestRateBps, uint256 prepayPenaltyBps, uint256 gracePeriodSeconds, uint256 termSeconds, uint256 startedAt, uint256 dueAt, uint8 state, uint256 totalPrincipal, uint256 drawnPrincipal, uint256 outstandingPrincipal, uint256 lastAccrualAt, uint256 totalInterestPaid, uint256 totalPrincipalPaid, uint8 numTranches, tuple(uint256 amount, uint256 releaseAt, bool drawn) tranche0, tuple(uint256 amount, uint256 releaseAt, bool drawn) tranche1, tuple(uint256 amount, uint256 releaseAt, bool drawn) tranche2, string propertyAddress))',
  'function accruedInterest(bytes32 loanId) view returns (uint256)',
  'function nextPaymentDue(bytes32 loanId) view returns (uint256 amount, uint256 dueTimestamp)',
  'function paymentSchedule(bytes32 loanId) view returns (uint256[] amounts, uint256[] dueDates)',
  'function daysDelinquent(bytes32 loanId) view returns (uint256)',
  'event LoanOriginated(bytes32 indexed loanId, address indexed borrower, uint256 totalPrincipal, string propertyAddress)',
  'event LoanApproved(bytes32 indexed loanId)',
  'event DrawDisbursed(bytes32 indexed loanId, uint8 trancheIndex, uint256 amount)',
  'event LoanPayment(bytes32 indexed loanId, address indexed payer, uint256 paymentAmount, uint256 interestPortion, uint256 principalPortion, uint256 remainingPrincipal)',
  'event LoanPrepaid(bytes32 indexed loanId, uint256 penaltyAmount)',
  'event LoanDelinquent(bytes32 indexed loanId)',
  'event LoanCured(bytes32 indexed loanId)',
  'event LoanDefaulted(bytes32 indexed loanId)',
  'event LoanRepaid(bytes32 indexed loanId)',
  'event LoanAdminClosed(bytes32 indexed loanId)',
] as const;

// AXIOMCreditMarket — permissioned LP pool (ERC-3643 identity-gated)
export const CREDIT_MARKET_ABI = [
  'function depositLiquidity(uint256 amountUsd) external',
  'function withdrawLiquidity(uint256 sharesToBurn) external',
  'function commitLiquidity(bytes32 loanId, uint256 amountUsd) external',
  'function recordDisbursement(bytes32 loanId, uint256 amountUsd) external',
  'function distributeRepayment(bytes32 loanId, uint256 principalReturned, uint256 interestAmount) external',
  'function claimInterest() external',
  'function setReserveRatio(uint256 newBps) external',
  'function availableLiquidity() view returns (uint256)',
  'function totalPoolValue() view returns (uint256)',
  'function sharePrice() view returns (uint256)',
  'function pendingInterest(address lp) view returns (uint256)',
  'function isLpVerified(address lp) view returns (bool)',
  'function lpShares(address) view returns (uint256)',
  'function totalLpShares() view returns (uint256)',
  'function totalDeposited() view returns (uint256)',
  'function totalInterestReceived() view returns (uint256)',
  'function loanCommitment(bytes32) view returns (uint256)',
  'function reserveRatioBps() view returns (uint256)',
  'event LiquidityDeposited(address indexed lp, uint256 amountUsd, uint256 sharesIssued)',
  'event LiquidityWithdrawn(address indexed lp, uint256 axusdOut, uint256 sharesBurned)',
  'event LiquidityCommitted(bytes32 indexed loanId, uint256 amount)',
  'event RepaymentReceived(bytes32 indexed loanId, uint256 principalReturned, uint256 interestReceived)',
  'event InterestClaimed(address indexed lp, uint256 amount)',
] as const;
`;

  const outPath = path.join(__dirname, "../src/config/creditMarket.generated.ts");
  fs.writeFileSync(outPath, content, "utf8");
  console.log("   ✓ Wrote:", outPath);
}

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("═══════════════════════════════════════════════════════════════");
  console.log("  AXIOM CREDIT MARKET v4 — DEPLOYMENT");
  console.log("  AXIOMFixedLoan (loan engine) + AXIOMCreditMarket (LP pool)");
  console.log("═══════════════════════════════════════════════════════════════");
  console.log("\nDeployer:", deployer.address);
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Balance:", ethers.formatEther(balance), "ETH");
  console.log("AXUSD:", ACTIVE_AXUSD);
  console.log("IdentityRegistry:", IDENTITY_REGISTRY);
  const network = await ethers.provider.getNetwork();
  console.log("Network ChainId:", network.chainId, "\n");

  if (network.chainId !== 42161n) {
    throw new Error(`Wrong network. Expected Arbitrum One (42161), got ${network.chainId}`);
  }
  if (balance < ethers.parseEther("0.002")) {
    throw new Error("Insufficient ETH balance (need ≥ 0.002 ETH)");
  }

  // ── 1. Deploy AXIOMFixedLoan ──────────────────────────────────────────────
  console.log("[1/5] Deploying AXIOMFixedLoan (loan engine)...");
  const FixedLoanFactory = await ethers.getContractFactory("AXIOMFixedLoan");
  const fixedLoan = await FixedLoanFactory.deploy(ACTIVE_AXUSD, IDENTITY_REGISTRY);
  await fixedLoan.waitForDeployment();
  const fixedLoanAddress = await fixedLoan.getAddress();
  console.log("   ✓ AXIOMFixedLoan:", fixedLoanAddress);
  await sleep(3000);

  // ── 2. Deploy AXIOMCreditMarket ───────────────────────────────────────────
  console.log("\n[2/5] Deploying AXIOMCreditMarket (LP pool, ERC-3643 gated)...");
  const CreditMarketFactory = await ethers.getContractFactory("AXIOMCreditMarket");
  const creditMarket = await CreditMarketFactory.deploy(ACTIVE_AXUSD, IDENTITY_REGISTRY);
  await creditMarket.waitForDeployment();
  const creditMarketAddress = await creditMarket.getAddress();
  console.log("   ✓ AXIOMCreditMarket:", creditMarketAddress);
  await sleep(3000);

  // ── 3. Wire: grant OPERATOR_ROLE on FixedLoan to CreditMarket operator ───
  console.log("\n[3/5] Wiring contracts...");
  const OPERATOR_ROLE = ethers.keccak256(ethers.toUtf8Bytes("OPERATOR_ROLE"));
  const grantTx = await fixedLoan.grantRole(OPERATOR_ROLE, creditMarketAddress);
  await grantTx.wait();
  const wireTx = grantTx.hash;
  console.log("   ✓ OPERATOR_ROLE on FixedLoan granted to CreditMarket, tx:", wireTx);
  await sleep(3000);

  // ── 4. Write generated config ─────────────────────────────────────────────
  console.log("\n[4/5] Writing src/config/creditMarket.generated.ts...");
  const deployedAt = new Date().toISOString().slice(0, 10);
  writeGeneratedConfig({
    deployer: deployer.address,
    axusd: ACTIVE_AXUSD,
    identityRegistry: IDENTITY_REGISTRY,
    creditMarket: creditMarketAddress,
    fixedLoan: fixedLoanAddress,
    chainId: network.chainId,
    wireTx,
    deployedAt,
  });

  // ── 5. Print summary ──────────────────────────────────────────────────────
  console.log("\n═══════════════════════════════════════════════════════════════");
  console.log("  DEPLOYMENT COMPLETE");
  console.log("═══════════════════════════════════════════════════════════════");
  console.log(`  AXIOMFixedLoan:    ${fixedLoanAddress}`);
  console.log(`  AXIOMCreditMarket: ${creditMarketAddress}`);
  console.log(`  AXUSD (vault):     ${ACTIVE_AXUSD}`);
  console.log(`  IdentityRegistry:  ${IDENTITY_REGISTRY}`);
  console.log(`  Wire tx:           ${wireTx}`);
  console.log("═══════════════════════════════════════════════════════════════\n");

  // ── 6. Verify on Blockscout ────────────────────────────────────────────────
  console.log("[5/5] Verifying contracts on block explorer...");
  await sleep(10000);
  await verifyContract(fixedLoanAddress, [ACTIVE_AXUSD, IDENTITY_REGISTRY]);
  await verifyContract(creditMarketAddress, [ACTIVE_AXUSD, IDENTITY_REGISTRY]);

  // Update activeContracts.generated.ts
  const activeContractsPath = path.join(__dirname, "../src/config/activeContracts.generated.ts");
  let activeContracts = fs.readFileSync(activeContractsPath, "utf8");
  activeContracts = activeContracts
    .replace(/CREDIT_MARKET_ADDRESS = '0x[0-9a-fA-F]+'/, `CREDIT_MARKET_ADDRESS = '${creditMarketAddress}'`)
    .replace(/FIXED_LOAN_NFT_ADDRESS = '0x[0-9a-fA-F]+'/, `FIXED_LOAN_NFT_ADDRESS = '${fixedLoanAddress}'`);
  fs.writeFileSync(activeContractsPath, activeContracts, "utf8");
  console.log("   ✓ Updated activeContracts.generated.ts");

  console.log("\nDeployment script complete.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
