/**
 * Wire v2 contracts: MINTER_ROLE + setFixedLoanNFT for redeployed contracts
 */
import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";
import { ACTIVE_AXUSD } from "../src/config/activeContracts.generated";

const FIXED_LOAN_ADDRESS    = "0x8190C1cf5b50BdCa8f18A1fF1b211ffc78750b81";
const CREDIT_MARKET_ADDRESS = "0x701BB67B22275bb395642C66f18a26d65E374917";

const CREDIT_MARKET_ABI = [
  "function setFixedLoanNFT(address nft) external",
  "function fixedLoanNFT() view returns (address)",
];

const FIXED_LOAN_ABI = [
  "function grantRole(bytes32 role, address account) external",
  "function hasRole(bytes32 role, address account) view returns (bool)",
];

async function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  const [deployer] = await ethers.getSigners();
  const network = await ethers.provider.getNetwork();
  console.log("Signer:", deployer.address, "ChainId:", network.chainId);

  const creditMarket = new ethers.Contract(CREDIT_MARKET_ADDRESS, CREDIT_MARKET_ABI, deployer);
  const fixedLoan    = new ethers.Contract(FIXED_LOAN_ADDRESS, FIXED_LOAN_ABI, deployer);
  const MINTER_ROLE  = ethers.keccak256(ethers.toUtf8Bytes("MINTER_ROLE"));

  // Check current state
  const currentNFT  = await creditMarket.fixedLoanNFT();
  const hasMinter   = await fixedLoan.hasRole(MINTER_ROLE, CREDIT_MARKET_ADDRESS);
  console.log("Current fixedLoanNFT:", currentNFT);
  console.log("CreditMarket has MINTER_ROLE:", hasMinter);

  if (!hasMinter) {
    console.log("Granting MINTER_ROLE...");
    const tx = await fixedLoan.grantRole(MINTER_ROLE, CREDIT_MARKET_ADDRESS);
    await tx.wait();
    console.log("✓ MINTER_ROLE granted, tx:", tx.hash);
    await sleep(4000);
  }

  if (currentNFT.toLowerCase() !== FIXED_LOAN_ADDRESS.toLowerCase()) {
    console.log("Setting fixedLoanNFT to:", FIXED_LOAN_ADDRESS);
    const tx = await creditMarket.setFixedLoanNFT(FIXED_LOAN_ADDRESS);
    await tx.wait();
    console.log("✓ setFixedLoanNFT, tx:", tx.hash);
    await sleep(2000);

    const wireTx = tx.hash;

    // Write generated config
    const operatorRole = ethers.keccak256(ethers.toUtf8Bytes("OPERATOR_ROLE"));
    const minterRole   = MINTER_ROLE;
    const deployedAt   = "2026-03-22";

    const content = `/**
 * AXIOM Credit Market — Deployed Contract Addresses
 * Generated by scripts/deploy-credit-market.ts (wired by wire-credit-market-v2.ts)
 * Deployed: ${deployedAt} on Arbitrum One (chainId: 42161)
 *
 * Verification:
 *   AXIOMFixedLoan:    https://arbitrum.blockscout.com/address/${FIXED_LOAN_ADDRESS}#code
 *   AXIOMCreditMarket: https://arbitrum.blockscout.com/address/${CREDIT_MARKET_ADDRESS}#code
 */

export const CREDIT_MARKET_DEPLOYMENT = {
  network:           'Arbitrum One',
  chainId:           42161,
  deployedAt:        '${deployedAt}',
  deployer:          '${deployer.address}',

  axusd:             '${ACTIVE_AXUSD}',
  creditMarket:      '${CREDIT_MARKET_ADDRESS}',
  fixedLoanNFT:      '${FIXED_LOAN_ADDRESS}',

  explorerBase:      'https://arbitrum.blockscout.com',
  wireTx:            '${wireTx}',

  roles: {
    operatorRole:    '${operatorRole}',
    minterRole:      '${minterRole}',
    adminRole:       '0x0000000000000000000000000000000000000000000000000000000000000000',
  },

  loanStatusMap: {
    0: 'PENDING',
    1: 'APPROVED',
    2: 'ACTIVE',
    3: 'DELINQUENT',
    4: 'REPAID',
    5: 'DEFAULTED',
  } as Record<number, string>,
} as const;

export const CREDIT_MARKET_ABI = [
  'function originateLoan(bytes32 loanId, address borrower, uint256 principal, uint256 rateBps, uint256 feeBps, uint256 termDays, string calldata propAddress) external',
  'function approveLoan(bytes32 loanId) external',
  'function fundLoan(bytes32 loanId) external',
  'function markDelinquent(bytes32 loanId) external',
  'function cureDelinquent(bytes32 loanId) external',
  'function defaultLoan(bytes32 loanId) external',
  'function repayLoan(bytes32 loanId, uint256 paymentUsd6) external',
  'function depositLiquidity(uint256 amountUsd6) external',
  'function withdrawLiquidity(uint256 sharesToBurn) external',
  'function addLpAllowlist(address lp) external',
  'function removeLpAllowlist(address lp) external',
  'function isLpAllowed(address lp) view returns (bool)',
  'function getLoan(bytes32 loanId) view returns (tuple(bytes32 loanId, address borrower, uint256 principalUsd6, uint256 interestRateBps, uint256 originationFeeUsd6, uint256 termSeconds, uint8 status, uint256 fundedAt, uint256 dueAt, uint256 lastAccrualAt, uint256 totalRepaidUsd6, uint256 totalInterestPaidUsd6, string propertyAddress))',
  'function accruedInterest(bytes32 loanId) view returns (uint256)',
  'function totalDeposited() view returns (uint256)',
  'function totalDeployed() view returns (uint256)',
  'function totalWithdrawn() view returns (uint256)',
  'function lpShares(address) view returns (uint256)',
  'function totalLpShares() view returns (uint256)',
  'function availableLiquidity() view returns (uint256)',
  'function fixedLoanNFT() view returns (address)',
  'event LoanOriginated(bytes32 indexed loanId, address indexed borrower, uint256 principalUsd6, string propertyAddress)',
  'event LoanApproved(bytes32 indexed loanId)',
  'event LoanFunded(bytes32 indexed loanId, address indexed borrower, uint256 principalUsd6)',
  'event LoanRepayment(bytes32 indexed loanId, address indexed payer, uint256 paymentUsd6, uint256 interestPortion, uint256 principalPortion, uint256 remainingPrincipal)',
  'event LoanRepaid(bytes32 indexed loanId)',
  'event LoanDelinquent(bytes32 indexed loanId)',
  'event LoanCured(bytes32 indexed loanId)',
  'event LoanDefaulted(bytes32 indexed loanId)',
] as const;

export const FIXED_LOAN_ABI = [
  'function mintReceipt(bytes32 loanId, address borrower, uint256 principalUsd6, uint256 rateBps, uint256 termDays, uint256 dueAt, string calldata propAddress) external returns (uint256)',
  'function burnReceipt(bytes32 loanId) external',
  'function loanIdToTokenId(bytes32 loanId) view returns (uint256)',
  'function tokenURI(uint256 tokenId) view returns (string)',
  'function ownerOf(uint256 tokenId) view returns (address)',
] as const;
`;
    const outPath = path.join(__dirname, "../src/config/creditMarket.generated.ts");
    fs.writeFileSync(outPath, content, "utf8");
    console.log("✓ Written:", outPath);
  } else {
    console.log("✓ Already wired correctly");
  }

  const after = await creditMarket.fixedLoanNFT();
  console.log("✓ fixedLoanNFT confirmed:", after);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
