/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CountryAllowModule } from './CountryAllowModule.js';
export type { ITokenRegistryProvider } from './ITokenRegistryProvider.js';